# Generated by Django 2.2.4 on 2020-11-03 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaObjectPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(blank=True, null=True, upload_to='object/schema/', verbose_name='Схема')),
                ('object', models.ManyToManyField(blank=True, related_name='schema_object_photo', to='objects.Object', verbose_name='Схема')),
            ],
        ),
        migrations.CreateModel(
            name='OrderObjectPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(blank=True, upload_to='object/order/', verbose_name='Схема')),
                ('object', models.ManyToManyField(blank=True, related_name='order_object_photo', to='objects.Object', verbose_name='Распоряжение')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('src', models.ImageField(blank=True, upload_to='object/orders/', verbose_name='Распоряжение')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile')),
            ],
            options={
                'verbose_name': 'Распоряжение',
                'verbose_name_plural': 'Распоряжения',
                'ordering': ('id',),
            },
        ),
    ]
