# Generated by Django 2.2.4 on 2020-08-17 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО')),
                ('outfit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outfit_worker', to='objects.Outfit')),
            ],
            options={
                'verbose_name': 'Сотрудник предприятия',
                'verbose_name_plural': 'Сотрудники предприятий',
            },
        ),
    ]
