# Generated by Django 2.2.4 on 2020-11-03 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('value', models.IntegerField(verbose_name='Значение')),
                ('auto_add', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Количество каналов',
                'verbose_name_plural': 'Количество каналов',
            },
        ),
        migrations.AlterField(
            model_name='object',
            name='num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество задейственных каналов'),
        ),
        migrations.AlterField(
            model_name='object',
            name='total_amount_active_channels',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='total_amount_channels',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
