# Generated by Django 2.2.4 on 2020-09-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='total_amount_channels',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
