# Generated by Django 2.2.4 on 2021-08-23 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название')),
                ('num_channel', models.CharField(blank=True, max_length=500, null=True, verbose_name='Номер канала')),
                ('ip_address', models.CharField(blank=True, max_length=500, null=True, verbose_name='IP')),
                ('resource', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Ресурс')),
                ('comments', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Примечание')),
                ('outfit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tv_out', to='objects.Outfit')),
            ],
            options={
                'verbose_name': 'Каналы IPTV',
                'verbose_name_plural': 'Каналы IPTV',
                'ordering': ('id',),
            },
        ),
    ]
