# Generated by Django 2.2.4 on 2020-09-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_object_total_amount_channels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ip',
            options={'ordering': ('id',), 'verbose_name': 'ИП', 'verbose_name_plural': 'ИП'},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'ordering': ('id',), 'verbose_name': 'Линия передачи/Обьект/Тракт', 'verbose_name_plural': 'Линия передачи/Обьект/Тракт'},
        ),
        migrations.AddField(
            model_name='object',
            name='total_amount_active_channels',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='num',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Количество задейственных каналов'),
        ),
    ]
