# Generated by Django 2.2.4 on 2021-08-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_tv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TV',
            new_name='IPTV',
        ),
    ]
