# Generated by Django 2.2.4 on 2020-11-03 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_auto_20201103_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='amount_channels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_channel', to='objects.AmountChannel', verbose_name='Количество каналов'),
        ),
    ]
