# Generated by Django 2.2.4 on 2020-06-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_auto_20200612_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='index',
        ),
        migrations.AddField(
            model_name='category',
            name='index',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Обозначение'),
        ),
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
    ]
