# Generated by Django 2.2.4 on 2020-06-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_auto_20200612_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='not_in_use',
        ),
        migrations.AddField(
            model_name='object',
            name='save_in',
            field=models.BooleanField(blank=True, null=True, verbose_name='Сохранить'),
        ),
    ]
