# Generated by Django 2.2.4 on 2020-11-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_auto_20201103_1130'),
        ('objects', '0003_historicalip_historicalobject_historicalorder_historicaloutfit_historicalpoint'),
    ]

    operations = [
    ]
