# Generated by Django 2.2.4 on 2020-09-16 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_auto_20200914_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='id_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='objects.Object'),
        ),
    ]
