# Generated by Django 2.2.4 on 2021-08-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_auto_20210823_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iptv',
            name='num_channel',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Номер канала'),
        ),
    ]
