# Generated by Django 2.2.4 on 2020-09-17 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_auto_20200916_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='point_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ip_point', to='objects.Point'),
        ),
    ]
