# Generated by Django 2.2.4 on 2020-11-03 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_merge_20201103_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalobject',
            name='amount_channels',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='objects.AmountChannel', verbose_name='Количество каналов'),
        ),
        migrations.AlterField(
            model_name='historicalobject',
            name='num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество задейственных каналов'),
        ),
        migrations.AlterField(
            model_name='object',
            name='total_amount_active_channels',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='total_amount_channels',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
