# Generated by Django 2.2.4 on 2020-09-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_auto_20200917_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ip',
            options={'ordering': ('id',), 'verbose_name': 'ИП', 'verbose_name_plural': 'ИПы'},
        ),
    ]
