# Generated by Django 2.2.4 on 2020-08-21 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_auto_20200821_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='tpo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.TPO'),
        ),
        migrations.AlterField(
            model_name='object',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obj_category', to='objects.Category'),
        ),
        migrations.AlterField(
            model_name='object',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='object',
            name='destination1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obj_dest1', to='objects.IP'),
        ),
        migrations.AlterField(
            model_name='object',
            name='destination2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obj_dest2', to='objects.IP'),
        ),
        migrations.AlterField(
            model_name='object',
            name='id_outfit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obj_out', to='objects.Outfit'),
        ),
        migrations.AlterField(
            model_name='object',
            name='maker_trassa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maker', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='object',
            name='our',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obj_our', to='objects.TypeOfLocation'),
        ),
        migrations.AlterField(
            model_name='object',
            name='point1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obj_point', to='objects.Point', verbose_name='ИП приема'),
        ),
        migrations.AlterField(
            model_name='object',
            name='point2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obj_point2', to='objects.Point', verbose_name='ИП пер'),
        ),
        migrations.AlterField(
            model_name='object',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obj_system', to='objects.System'),
        ),
        migrations.AlterField(
            model_name='object',
            name='type_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obj_type_line', to='objects.LineType'),
        ),
        migrations.AlterField(
            model_name='object',
            name='type_of_trakt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obj_trakt_type', to='objects.TypeOfTrakt'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='tpo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.TPO'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='type_outfit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.TypeOfLocation'),
        ),
        migrations.AlterField(
            model_name='transitobject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile'),
        ),
        migrations.DeleteModel(
            name='Trassa',
        ),
    ]
