# Generated by Django 2.2.4 on 2020-11-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_auto_20201103_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalobject',
            name='total_amount_active_channels',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalobject',
            name='total_amount_channels',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='total_amount_active_channels',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='total_amount_channels',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
