# Generated by Django 2.2.4 on 2020-09-21 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_auto_20200917_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTypeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип линии АК',
                'verbose_name_plural': 'Типы линии АК',
            },
        ),
        migrations.AddField(
            model_name='linetype',
            name='analysis_type_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_type', to='objects.AnalysisTypeLine'),
        ),
    ]
