# Generated by Django 2.2.4 on 2020-09-18 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_auto_20200917_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainLineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('line_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_type', to='objects.LineType')),
            ],
            options={
                'verbose_name': 'Категория типа линии',
                'verbose_name_plural': 'Категории типов линии',
            },
        ),
    ]
