# Generated by Django 2.2.4 on 2020-11-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_auto_20201111_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='orderobjectphoto',
            name='object',
        ),
        migrations.RemoveField(
            model_name='schemaobjectphoto',
            name='object',
        ),
        migrations.AddField(
            model_name='historicalobject',
            name='order',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='№ и дата распоряжения'),
        ),
        migrations.AddField(
            model_name='historicalobject',
            name='src',
            field=models.TextField(blank=True, max_length=100, verbose_name='Скан распоряжения'),
        ),
        migrations.AddField(
            model_name='historicalpoint',
            name='region',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='historicalpoint',
            name='type_equipment',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Тип оборудования'),
        ),
        migrations.AddField(
            model_name='object',
            name='order',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='№ и дата распоряжения'),
        ),
        migrations.AddField(
            model_name='object',
            name='src',
            field=models.ImageField(blank=True, upload_to='object/orders/', verbose_name='Скан распоряжения'),
        ),
        migrations.AddField(
            model_name='point',
            name='region',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='point',
            name='type_equipment',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Тип оборудования'),
        ),
        migrations.DeleteModel(
            name='HistoricalOrder',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderObjectPhoto',
        ),
        migrations.DeleteModel(
            name='SchemaObjectPhoto',
        ),
    ]
