# Generated by Django 2.2.4 on 2020-08-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_auto_20200821_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpo',
            name='name',
            field=models.CharField(error_messages={'invalid': 'Это поле обязательно.'}, max_length=100, verbose_name='Название'),
        ),
    ]
