# Generated by Django 2.2.4 on 2020-09-18 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_mainlinetype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainlinetype',
            options={'verbose_name': 'Тип линии', 'verbose_name_plural': 'Типы линии'},
        ),
        migrations.RemoveField(
            model_name='mainlinetype',
            name='line_type',
        ),
        migrations.AddField(
            model_name='linetype',
            name='main_line_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_line_type', to='objects.MainLineType'),
        ),
    ]
