# Generated by Django 2.2.4 on 2020-08-24 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_auto_20200821_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='object',
            options={'ordering': ('id',), 'verbose_name': 'Линия передачи/Обьект/Тракт', 'verbose_name_plural': 'Линия передачи/Обьект/Тракт'},
        ),
    ]
