# Generated by Django 2.2.4 on 2020-11-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_auto_20201120_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalobject',
            name='reserve_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Резерв'),
        ),
        migrations.AddField(
            model_name='object',
            name='reserve_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Резерв'),
        ),
    ]
