# Generated by Django 2.2.4 on 2020-11-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0008_auto_20201123_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalobject',
            name='reserve_value',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Резерв'),
        ),
        migrations.AlterField(
            model_name='object',
            name='reserve_value',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Резерв'),
        ),
    ]
