# Generated by Django 2.2.4 on 2020-09-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0008_auto_20200918_1202'),
        ('objects', '0007_auto_20200921_1143'),
    ]

    operations = [
    ]
