# Generated by Django 2.2.4 on 2020-11-24 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0009_auto_20201123_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalobject',
            name='reserve_value',
        ),
        migrations.RemoveField(
            model_name='historicalobject',
            name='total_amount_active_channels',
        ),
        migrations.RemoveField(
            model_name='object',
            name='reserve_value',
        ),
        migrations.RemoveField(
            model_name='object',
            name='total_amount_active_channels',
        ),
        migrations.AlterField(
            model_name='historicalobject',
            name='amount_channels',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='objects.AmountChannel', verbose_name='Монтированные каналы'),
        ),
        migrations.AlterField(
            model_name='historicalobject',
            name='total_amount_channels',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Задействованные каналы'),
        ),
        migrations.AlterField(
            model_name='object',
            name='amount_channels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_channel', to='objects.AmountChannel', verbose_name='Монтированные каналы'),
        ),
        migrations.AlterField(
            model_name='object',
            name='total_amount_channels',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Задействованные каналы'),
        ),
    ]
