# Generated by Django 2.2.4 on 2020-09-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0009_merge_20200921_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainlinetype',
            options={'verbose_name': 'Тип линии АК', 'verbose_name_plural': 'Типы линии АК'},
        ),
        migrations.RemoveField(
            model_name='linetype',
            name='analysis_type_line',
        ),
        migrations.DeleteModel(
            name='AnalysisTypeLine',
        ),
    ]
