# Generated by Django 2.2.4 on 2020-08-25 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0010_auto_20200824_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name': 'Линия передачи/Обьект/Тракт', 'verbose_name_plural': 'Линия передачи/Обьект/Тракт'},
        ),
    ]
