# Generated by Django 2.2.4 on 2020-11-24 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0010_auto_20201124_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalobject',
            name='num',
        ),
        migrations.RemoveField(
            model_name='object',
            name='num',
        ),
    ]
