# Generated by Django 2.2.4 on 2020-11-27 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0011_auto_20201124_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalobject',
            name='trakt',
        ),
        migrations.RemoveField(
            model_name='object',
            name='trakt',
        ),
    ]
