# Generated by Django 2.2.4 on 2020-09-01 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0011_auto_20200825_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outfitworker',
            options={'ordering': ('id',), 'verbose_name': 'Сотрудник предприятия', 'verbose_name_plural': 'Сотрудники предприятий'},
        ),
    ]
