# Generated by Django 2.2.4 on 2020-11-30 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0012_auto_20201127_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderObjectPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.FileField(blank=True, null=True, upload_to='', verbose_name='Схема')),
                ('object', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_object_photo', to='objects.Object', verbose_name='Распоряжение')),
            ],
        ),
    ]
