# Generated by Django 2.2.4 on 2020-11-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0013_orderobjectphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderobjectphoto',
            name='src',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Схема'),
        ),
    ]
