# Generated by Django 2.2.4 on 2020-12-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0014_auto_20201130_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpoint',
            name='point',
            field=models.CharField(db_index=True, max_length=100, verbose_name='ИП'),
        ),
        migrations.AlterField(
            model_name='point',
            name='point',
            field=models.CharField(max_length=100, unique=True, verbose_name='ИП'),
        ),
    ]
