# Generated by Django 2.2.4 on 2020-12-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0015_auto_20201214_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderobjectphoto',
            name='src',
            field=models.FileField(blank=True, null=True, upload_to='object/orders/'),
        ),
    ]
