# Generated by Django 2.2.4 on 2020-12-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0016_auto_20201215_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='src',
            field=models.ImageField(blank=True, upload_to='files/', verbose_name='Скан распоряжения'),
        ),
        migrations.AlterField(
            model_name='orderobjectphoto',
            name='src',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
