# Generated by Django 2.2.4 on 2021-01-04 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0017_auto_20201216_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Потребитель',
                'verbose_name_plural': 'Потребители',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Индекс назначения КО', 'verbose_name_plural': 'Индекс назначения КО'},
        ),
        migrations.AddField(
            model_name='historicalobject',
            name='consumer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='objects.Consumer'),
        ),
        migrations.AddField(
            model_name='object',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obj_consumer', to='objects.Consumer'),
        ),
    ]
