# Generated by Django 2.2.4 on 2021-01-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0018_auto_20210104_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amountchannel',
            old_name='auto_add',
            new_name='is_read_only',
        ),
    ]
