# Generated by Django 2.2.4 on 2021-01-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0008_auto_20210119_1201'),
        ('objects', '0019_auto_20210112_1237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InOut',
        ),
        migrations.RemoveField(
            model_name='historicalobject',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='historicalobject',
            name='inter_code',
        ),
        migrations.RemoveField(
            model_name='historicalobject',
            name='save_in',
        ),
        migrations.RemoveField(
            model_name='object',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='object',
            name='inter_code',
        ),
        migrations.RemoveField(
            model_name='object',
            name='save_in',
        ),
    ]
