# Generated by Django 2.2.4 on 2021-02-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0021_bug'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpoint',
            name='total_point_channels',
            field=models.IntegerField(default=0, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='point',
            name='total_point_channels',
            field=models.IntegerField(default=0, verbose_name='Значение'),
        ),
    ]
