# Generated by Django 2.2.4 on 2021-02-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0022_auto_20210210_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpoint',
            name='total_point_channels',
        ),
        migrations.RemoveField(
            model_name='point',
            name='total_point_channels',
        ),
        migrations.AddField(
            model_name='historicalpoint',
            name='total_point_channels_KLS',
            field=models.IntegerField(default=0, verbose_name='Значение_КЛС'),
        ),
        migrations.AddField(
            model_name='historicalpoint',
            name='total_point_channels_RRL',
            field=models.IntegerField(default=0, verbose_name='Значение_ЦРРЛ'),
        ),
        migrations.AddField(
            model_name='point',
            name='total_point_channels_KLS',
            field=models.IntegerField(default=0, verbose_name='Значение_КЛС'),
        ),
        migrations.AddField(
            model_name='point',
            name='total_point_channels_RRL',
            field=models.IntegerField(default=0, verbose_name='Значение_ЦРРЛ'),
        ),
    ]
