# Generated by Django 2.2.4 on 2021-02-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0023_auto_20210210_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalobject',
            name='is_transit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='object',
            name='is_transit',
            field=models.BooleanField(default=False),
        ),
    ]
