# Generated by Django 2.2.4 on 2021-02-17 14:51

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0024_auto_20210211_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='reserve_transit',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='reserve_transit_obj1', to='objects.Object'),
        ),
        migrations.AddField(
            model_name='object',
            name='reserve_transit2',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='reserve_transit_obj2', to='objects.Object'),
        ),
    ]
