# Generated by Django 2.2.4 on 2021-04-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0026_auto_20210331_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloutfit',
            name='length_kls',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Протяженность кан*км КЛС'),
        ),
        migrations.AddField(
            model_name='historicaloutfit',
            name='length_rrl',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Протяженность кан*км РРЛ'),
        ),
        migrations.AddField(
            model_name='historicaloutfit',
            name='length_vls',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Протяженность кан*км ВЛС'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='length_kls',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Протяженность кан*км КЛС'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='length_rrl',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Протяженность кан*км РРЛ'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='length_vls',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Протяженность кан*км ВЛС'),
        ),
    ]
