# Generated by Django 2.2.4 on 2021-04-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0027_auto_20210405_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloutfit',
            name='corresponding_norm_kls',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Соответствующих норме КЛС'),
        ),
        migrations.AddField(
            model_name='historicaloutfit',
            name='corresponding_norm_rrl',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Соответствующих норме РРЛ'),
        ),
        migrations.AddField(
            model_name='historicaloutfit',
            name='corresponding_norm_vls',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Соответствующих норме ВЛС'),
        ),
        migrations.AddField(
            model_name='historicaloutfit',
            name='total_number_kls',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Общее количество линейных трактов КЛС'),
        ),
        migrations.AddField(
            model_name='historicaloutfit',
            name='total_number_rrl',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Общее количество линейных трактов РРЛ'),
        ),
        migrations.AddField(
            model_name='historicaloutfit',
            name='total_number_vls',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Общее количество линейных трактов ВЛС'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='corresponding_norm_kls',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Соответствующих норме КЛС'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='corresponding_norm_rrl',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Соответствующих норме РРЛ'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='corresponding_norm_vls',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Соответствующих норме ВЛС'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='total_number_kls',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Общее количество линейных трактов КЛС'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='total_number_rrl',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Общее количество линейных трактов РРЛ'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='total_number_vls',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Общее количество линейных трактов ВЛС'),
        ),
    ]
