# Generated by Django 2.2.4 on 2021-04-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0028_auto_20210405_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountchannel',
            name='name',
            field=models.CharField(max_length=550, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='index',
            field=models.CharField(max_length=500, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Обозначение'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='name',
            field=models.CharField(max_length=550, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='historicalobject',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='historicalobject',
            name='comments_GOZ',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Примечание(ГОЗ)'),
        ),
        migrations.AlterField(
            model_name='historicalobject',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='historicalobject',
            name='order',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='№ и дата распоряжения'),
        ),
        migrations.AlterField(
            model_name='historicaloutfit',
            name='adding',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='historicaloutfit',
            name='num_outfit',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='historicaloutfit',
            name='outfit',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Аббревиатура'),
        ),
        migrations.AlterField(
            model_name='historicalpoint',
            name='point',
            field=models.CharField(db_index=True, max_length=500, verbose_name='ИП'),
        ),
        migrations.AlterField(
            model_name='historicalpoint',
            name='region',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='historicalpoint',
            name='type_equipment',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='Тип оборудования'),
        ),
        migrations.AlterField(
            model_name='linetype',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='mainlinetype',
            name='name',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='object',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='object',
            name='comments_GOZ',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Примечание(ГОЗ)'),
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='object',
            name='order',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='№ и дата распоряжения'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='adding',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='num_outfit',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='outfit',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Аббревиатура'),
        ),
        migrations.AlterField(
            model_name='outfitworker',
            name='name',
            field=models.CharField(max_length=500, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='point',
            name='point',
            field=models.CharField(max_length=500, unique=True, verbose_name='ИП'),
        ),
        migrations.AlterField(
            model_name='point',
            name='region',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='point',
            name='type_equipment',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='Тип оборудования'),
        ),
        migrations.AlterField(
            model_name='tpo',
            name='index',
            field=models.CharField(max_length=500, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='tpo',
            name='name',
            field=models.CharField(error_messages={'invalid': 'Это поле обязательно.'}, max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='typeoflocation',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='typeoftrakt',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
    ]
