# Generated by Django 2.2.4 on 2021-04-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0029_auto_20210421_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalobject',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='object',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
