# Generated by Django 2.2.4 on 2021-04-30 15:43

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0030_auto_20210427_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('trassa', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='transits', to='objects.Object')),
            ],
        ),
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bridges', to='objects.Object')),
                ('transit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='can_see', to='objects.Transit')),
            ],
        ),
    ]
