# Generated by Django 2.2.4 on 2021-04-27 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0030_auto_20210427_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalobject',
            name='is_main',
        ),
        migrations.RemoveField(
            model_name='object',
            name='is_main',
        ),
    ]
