# Generated by Django 2.2.4 on 2021-05-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0031_auto_20210427_1644'),
        ('objects', '0032_transit_create_circuit_transit'),
    ]

    operations = [
    ]
