# Generated by Django 2.2.4 on 2021-06-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0033_merge_20210506_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='reserve_transit',
        ),
        migrations.RemoveField(
            model_name='object',
            name='reserve_transit2',
        ),
        migrations.RemoveField(
            model_name='object',
            name='transit',
        ),
        migrations.RemoveField(
            model_name='object',
            name='transit2',
        ),
    ]
