# Generated by Django 2.2.4 on 2021-06-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0035_transit_is_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transit',
            name='is_modified',
        ),
    ]
