# Generated by Django 2.2.4 on 2020-07-17 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form51', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderphoto',
            old_name='order',
            new_name='src',
        ),
        migrations.RenameField(
            model_name='schemaphoto',
            old_name='schema',
            new_name='src',
        ),
    ]
