# Generated by Django 2.2.4 on 2020-06-02 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forma51_v2', '0002_remove_forma_region'),
        ('dispatching', '0004_auto_20200602_2136'),
        ('form51', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form51',
            old_name='year',
            new_name='index_ko',
        ),
        migrations.RemoveField(
            model_name='form51',
            name='amount_inst_channels',
        ),
        migrations.RemoveField(
            model_name='form51',
            name='amount_inv_channels',
        ),
        migrations.RemoveField(
            model_name='form51',
            name='category',
        ),
        migrations.RemoveField(
            model_name='form51',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='form51',
            name='num',
        ),
        migrations.RemoveField(
            model_name='form51',
            name='point1',
        ),
        migrations.RemoveField(
            model_name='form51',
            name='point2',
        ),
        migrations.RemoveField(
            model_name='form51',
            name='region',
        ),
        migrations.RemoveField(
            model_name='form51',
            name='tpo1',
        ),
        migrations.RemoveField(
            model_name='form51',
            name='tpo2',
        ),
        migrations.RemoveField(
            model_name='form51',
            name='trassa',
        ),
        migrations.RemoveField(
            model_name='form51',
            name='type_line',
        ),
        migrations.AddField(
            model_name='form51',
            name='num_ouss',
            field=models.CharField(default=2, max_length=250, verbose_name='Номер распоряжения ОУСС'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form51',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='Примечание (№ID, МН, Аренда)'),
        ),
        migrations.AlterField(
            model_name='form51',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.Object', verbose_name='КО'),
        ),
        migrations.AlterField(
            model_name='form51',
            name='reserve',
            field=models.CharField(default=1, max_length=15, verbose_name='Резерва потока'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Form51Location',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
