# Generated by Django 2.2.4 on 2020-09-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form51', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form51',
            options={'ordering': ('id',), 'verbose_name': 'Форма 5.1', 'verbose_name_plural': 'Форма 5.1.'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('id',), 'verbose_name': 'Регионы', 'verbose_name_plural': 'Регион'},
        ),
    ]
