# Generated by Django 2.2.4 on 2020-11-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form51', '0002_historicalform51'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderphoto',
            name='src',
            field=models.ImageField(blank=True, null=True, upload_to='files/', verbose_name='Схема'),
        ),
        migrations.AlterField(
            model_name='schemaphoto',
            name='src',
            field=models.ImageField(blank=True, null=True, upload_to='files/', verbose_name='Схема'),
        ),
    ]
