# Generated by Django 2.2.4 on 2020-06-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form51', '0002_auto_20200602_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='form51',
            name='report_num',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер донесения'),
        ),
        migrations.AlterField(
            model_name='form51',
            name='index_ko',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Инд.КО'),
        ),
    ]
