# Generated by Django 2.2.4 on 2020-06-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_auto_20200518_2229'),
        ('form51', '0003_auto_20200603_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='form51',
            name='reserve_object',
            field=models.ManyToManyField(blank=True, null=True, related_name='reserve_objects', to='objects.Object', verbose_name='Трасса резерва потока'),
        ),
    ]
