# Generated by Django 2.2.4 on 2020-06-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form51', '0004_form51_reserve_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form51',
            name='index_ko',
        ),
    ]
