# Generated by Django 2.2.4 on 2021-01-04 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form51', '0004_auto_20201130_1211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.RemoveField(
            model_name='form51',
            name='num_ouss',
        ),
        migrations.RemoveField(
            model_name='form51',
            name='report_num',
        ),
        migrations.RemoveField(
            model_name='historicalform51',
            name='num_ouss',
        ),
        migrations.RemoveField(
            model_name='historicalform51',
            name='report_num',
        ),
        migrations.AddField(
            model_name='form51',
            name='comments',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='form51',
            name='num_order',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер распоряжения'),
        ),
        migrations.AddField(
            model_name='historicalform51',
            name='comments',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='historicalform51',
            name='num_order',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер распоряжения'),
        ),
        migrations.AlterField(
            model_name='form51',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='Арендатор'),
        ),
        migrations.AlterField(
            model_name='form51',
            name='reserve',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Наличие резерва'),
        ),
        migrations.AlterField(
            model_name='historicalform51',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer.Customer', verbose_name='Арендатор'),
        ),
        migrations.AlterField(
            model_name='historicalform51',
            name='reserve',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Наличие резерва'),
        ),
    ]
