# Generated by Django 2.2.4 on 2021-02-26 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form51', '0005_auto_20210104_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form51',
            name='reserve_object',
        ),
    ]
