# Generated by Django 2.2.4 on 2021-05-19 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form51', '0006_remove_form51_reserve_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemaphoto',
            name='form51',
        ),
        migrations.RemoveField(
            model_name='form51',
            name='num_order',
        ),
        migrations.RemoveField(
            model_name='form51',
            name='reserve',
        ),
        migrations.RemoveField(
            model_name='historicalform51',
            name='num_order',
        ),
        migrations.RemoveField(
            model_name='historicalform51',
            name='reserve',
        ),
        migrations.DeleteModel(
            name='OrderPhoto',
        ),
        migrations.DeleteModel(
            name='SchemaPhoto',
        ),
    ]
