# Generated by Django 2.2.4 on 2021-05-19 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form51', '0007_auto_20210519_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form51',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='form51',
            name='object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='objects.Object', verbose_name='КО'),
        ),
        migrations.AlterField(
            model_name='historicalform51',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
    ]
