# Generated by Django 2.2.4 on 2021-05-19 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form51', '0008_auto_20210519_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form51',
            options={'ordering': ('object',), 'verbose_name': 'Форма 5.1', 'verbose_name_plural': 'Форма 5.1.'},
        ),
    ]
