# Generated by Django 2.2.4 on 2021-05-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form51', '0009_auto_20210519_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form51',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='historicalform51',
            name='comments',
        ),
    ]
