# Generated by Django 2.2.4 on 2021-04-23 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='date',
        ),
    ]
