# Generated by Django 2.2.4 on 2020-05-05 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubdepartmentKT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Подотдел')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supdepartment', to='accounts.DepartmentKT', verbose_name='Подотдел')),
            ],
            options={
                'verbose_name': 'Подотдел',
                'verbose_name_plural': 'Подотделы',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='subdepartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_subdepartment', to='accounts.SubdepartmentKT', verbose_name='Подотдел пользователя'),
        ),
    ]
