# Generated by Django 2.2.4 on 2020-08-20 09:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentkt',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='subdepartmentkt',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supdepartment', to='accounts.DepartmentKT', verbose_name='Подотдел'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subdepartmentkt',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Подотдел'),
        ),
    ]
