# Generated by Django 2.2.4 on 2020-06-19 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200619_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='start_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='time',
        ),
        migrations.CreateModel(
            name='EntryAndExitLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журнал',
            },
        ),
    ]
