# Generated by Django 2.2.4 on 2020-06-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200619_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryandexitlog',
            name='time',
        ),
        migrations.AddField(
            model_name='entryandexitlog',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
