# Generated by Django 2.2.4 on 2020-06-20 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200619_1421'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntryAndExitLog',
            new_name='Log',
        ),
    ]
