# Generated by Django 2.2.4 on 2020-05-01 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус завка',
                'verbose_name_plural': 'Статусы заявок',
            },
        ),
        migrations.CreateModel(
            name='TypeOfStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Вид заявки')),
            ],
            options={
                'verbose_name': 'Вид заявка',
                'verbose_name_plural': 'Виды заявок',
            },
        ),
        migrations.CreateModel(
            name='TypeStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип заявки')),
            ],
            options={
                'verbose_name': 'Тип заявка',
                'verbose_name_plural': 'Типы заявок',
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=355, verbose_name='Адресс')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('telephone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер телефона')),
                ('home_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер домашнего телефона')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('date_from', models.DateTimeField(blank=True, null=True, verbose_name='От')),
                ('date_to', models.DateTimeField(blank=True, null=True, verbose_name='До')),
                ('specialist', models.CharField(blank=True, max_length=355, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile', verbose_name='Контактное лицо')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alarm_log.Status', verbose_name='Статус заявка')),
                ('type_of_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alarm_log.TypeOfStatement', verbose_name='Вид заявки')),
                ('type_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alarm_log.TypeStatement', verbose_name='Тип заявки')),
            ],
            options={
                'verbose_name': 'Статус завка',
                'verbose_name_plural': 'Статусы заявок',
            },
        ),
    ]
