# Generated by Django 2.2.4 on 2020-05-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm_log', '0003_auto_20200503_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shutdownlog',
            options={'verbose_name': 'Журнал отключений', 'verbose_name_plural': 'Журнал отключений'},
        ),
        migrations.AlterField(
            model_name='shutdownlog',
            name='shutdown_periods_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Период отключения'),
        ),
        migrations.AlterField(
            model_name='shutdownlog',
            name='shutdown_periods_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Период отключения'),
        ),
    ]
