# Generated by Django 2.2.4 on 2020-06-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forma51_v2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forma',
            name='region',
        ),
    ]
