# Generated by Django 2.2.4 on 2020-10-01 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificGravityOfLength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_length', models.IntegerField(blank=True, null=True)),
                ('coefficient', models.IntegerField(blank=True, null=True)),
                ('id_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.SpecificGravityOfLength')),
            ],
        ),
        migrations.CreateModel(
            name='SpecificGravityOfLengthTypeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, null=True)),
                ('specific_gravity_of_length', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.SpecificGravityOfLength')),
                ('type_line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.MainLineType')),
            ],
        ),
        migrations.CreateModel(
            name='OutfitItem5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.OutfitItem5')),
                ('outfit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.Outfit')),
                ('total_coefficient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysis.SpecificGravityOfLength')),
            ],
        ),
        migrations.CreateModel(
            name='Item7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile')),
            ],
            options={
                'verbose_name': 'п.7',
                'verbose_name_plural': 'п.7',
            },
        ),
        migrations.CreateModel(
            name='Item5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('outfit_period_of_time', models.IntegerField()),
                ('length', models.IntegerField(blank=True, null=True)),
                ('downtime', models.IntegerField(blank=True, null=True)),
                ('coefficient', models.IntegerField(blank=True, null=True)),
                ('outfit_item5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item5', to='analysis.OutfitItem5')),
                ('type_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.MainLineType')),
            ],
            options={
                'verbose_name': 'п.5',
                'verbose_name_plural': 'п.5',
            },
        ),
        migrations.CreateModel(
            name='FormAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('average_coefficient', models.IntegerField(blank=True, null=True)),
                ('coefficient', models.IntegerField(blank=True, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('coefficient_item5', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.OutfitItem5')),
                ('coefficient_item7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.Item7')),
                ('id_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.FormAnalysis')),
                ('outfit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.Outfit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile')),
            ],
            options={
                'verbose_name': 'ср.Кфт',
                'verbose_name_plural': 'ср.Кфт',
            },
        ),
    ]
