# Generated by Django 2.2.4 on 2020-09-21 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('dispatching', '0002_remove_event_period_of_time'),
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='Дата создания')),
                ('period_of_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Сумма часов, за которое устранили аварию')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile', verbose_name='Кем создан')),
                ('event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_analysis', to='dispatching.Event')),
            ],
            options={
                'verbose_name': 'Форма для АК',
                'verbose_name_plural': 'Форма для АК',
                'ordering': ('id',),
            },
        ),
        migrations.DeleteModel(
            name='AnalysisLineType',
        ),
    ]
