# Generated by Django 2.2.4 on 2020-10-13 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
        ('analysis', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='punkt7',
            name='outfit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='punkt7_outfit', to='objects.Outfit'),
        ),
        migrations.AddField(
            model_name='punkt7',
            name='punkt5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pinkt7_punkt5', to='analysis.Punkt5'),
        ),
        migrations.AddField(
            model_name='punkt5',
            name='all_coef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_coef_punkt5', to='analysis.All_Coefficient'),
        ),
        migrations.AddField(
            model_name='punkt5',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_punkt5', to='analysis.Country'),
        ),
        migrations.AddField(
            model_name='punkt5',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile', verbose_name='ФИО создателя'),
        ),
        migrations.AddField(
            model_name='punkt5',
            name='form_ak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='punkt5_form', to='analysis.FormAK'),
        ),
        migrations.AddField(
            model_name='punkt5',
            name='outfit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='punkt5_outfit', to='objects.Outfit'),
        ),
        migrations.AddField(
            model_name='formak',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_form', to='analysis.Country'),
        ),
        migrations.AddField(
            model_name='formak',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile', verbose_name='ФИО создателя'),
        ),
        migrations.AddField(
            model_name='formak',
            name='outfit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formak_outfit', to='objects.Outfit'),
        ),
        migrations.AddField(
            model_name='country_punkt7',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile', verbose_name='ФИО создателя'),
        ),
        migrations.AddField(
            model_name='country_punkt7',
            name='outfit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_punkt7_outfit', to='objects.Outfit'),
        ),
        migrations.AddField(
            model_name='country',
            name='outfit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_outfit', to='objects.Outfit'),
        ),
        migrations.AddField(
            model_name='averagecoef',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile', verbose_name='ФИО создателя'),
        ),
        migrations.AddField(
            model_name='averagecoef',
            name='outfit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avg_outfit', to='objects.Outfit'),
        ),
        migrations.AddField(
            model_name='averagecoef',
            name='punkt5_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avg_country_punkt5', to='analysis.Country'),
        ),
        migrations.AddField(
            model_name='averagecoef',
            name='punkt7_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avg_country_punkt7', to='analysis.Country_Punkt7'),
        ),
        migrations.AddField(
            model_name='averagecoef',
            name='total_coefficient_punkt5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avg_total_coef_punkt5', to='analysis.Punkt5'),
        ),
        migrations.AddField(
            model_name='averagecoef',
            name='total_coefficient_punkt7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avg_total_coef_punkt7', to='analysis.Punkt7'),
        ),
        migrations.AddField(
            model_name='all_coefficient',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_all_coef', to='analysis.Country'),
        ),
        migrations.AddField(
            model_name='all_coefficient',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile', verbose_name='ФИО создателя'),
        ),
        migrations.AddField(
            model_name='all_coefficient',
            name='outfit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_coef_outfit', to='objects.Outfit'),
        ),
    ]
