# Generated by Django 2.2.4 on 2020-10-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punkt5',
            name='KLS',
            field=models.IntegerField(blank=True, null=True, verbose_name='КЛС'),
        ),
        migrations.AlterField(
            model_name='punkt5',
            name='RRL',
            field=models.IntegerField(blank=True, null=True, verbose_name='РРЛ'),
        ),
        migrations.AlterField(
            model_name='punkt5',
            name='coefficient_kls',
            field=models.IntegerField(blank=True, null=True, verbose_name='Коэффициент качества (КЛС)'),
        ),
        migrations.AlterField(
            model_name='punkt5',
            name='coefficient_rrl',
            field=models.IntegerField(blank=True, null=True, verbose_name='Коэффициент качества (РРЛ)'),
        ),
        migrations.AlterField(
            model_name='punkt5',
            name='punkt5_total_outfit_kls',
            field=models.IntegerField(blank=True, null=True, verbose_name='Продолжительность всех ПВ кан*час(КЛС)'),
        ),
        migrations.AlterField(
            model_name='punkt5',
            name='punkt5_total_outfit_rrl',
            field=models.IntegerField(blank=True, null=True, verbose_name='Продолжительность всех ПВ кан*час(РРЛ)'),
        ),
        migrations.AlterField(
            model_name='punkt5',
            name='stops_kls',
            field=models.IntegerField(blank=True, null=True, verbose_name='Простои на 1000 кан*км (КЛС)'),
        ),
        migrations.AlterField(
            model_name='punkt5',
            name='stops_rrl',
            field=models.IntegerField(blank=True, null=True, verbose_name='Простои на 1000 кан*км (РРЛ)'),
        ),
        migrations.AlterField(
            model_name='punkt5',
            name='total_coefficient',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='punkt5',
            name='total_outfit_region_kls',
            field=models.IntegerField(blank=True, null=True, verbose_name='Протяженность кан*км зад.(КЛС)'),
        ),
        migrations.AlterField(
            model_name='punkt5',
            name='total_outfit_region_rrl',
            field=models.IntegerField(blank=True, null=True, verbose_name='Протяженность кан*км зад.(РРЛ)'),
        ),
        migrations.AlterField(
            model_name='punkt5',
            name='total_punkt5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общая протяж.кан*км'),
        ),
    ]
