# Generated by Django 2.2.4 on 2021-08-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form61rrl',
            name='traffic_capacity',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Пропускная способность'),
        ),
    ]
