# Generated by Django 2.2.4 on 2020-09-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20200921_1143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormAnalysis',
        ),
    ]
