# Generated by Django 2.2.4 on 2020-10-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20201001_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item5',
            name='outfit_period_of_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
