# Generated by Django 2.2.4 on 2020-10-29 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20201023_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formanalysis',
            name='outfit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.Outfit', unique=True, verbose_name='Предприятия'),
        ),
        migrations.AlterField(
            model_name='punkt5',
            name='outfit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.Outfit', unique=True, verbose_name='Предприятия'),
        ),
        migrations.AlterField(
            model_name='punkt7',
            name='outfit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.Outfit', unique=True, verbose_name='Предприятия'),
        ),
    ]
