# Generated by Django 2.2.4 on 2020-10-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20201013_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punkt5',
            name='all_coef',
        ),
        migrations.AddField(
            model_name='punkt5',
            name='KLS',
            field=models.FloatField(blank=True, null=True, verbose_name='КЛС'),
        ),
        migrations.AddField(
            model_name='punkt5',
            name='RRL',
            field=models.FloatField(blank=True, null=True, verbose_name='РРЛ'),
        ),
        migrations.AddField(
            model_name='punkt5',
            name='VLS',
            field=models.FloatField(blank=True, null=True, verbose_name='ВЛС'),
        ),
        migrations.AddField(
            model_name='punkt5',
            name='total_coefficient',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='punkt5',
            name='total_punkt5',
            field=models.FloatField(blank=True, null=True, verbose_name='Общая протяж.кан*км'),
        ),
        migrations.DeleteModel(
            name='All_Coefficient',
        ),
    ]
