# Generated by Django 2.2.4 on 2020-10-04 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
        ('analysis', '0003_auto_20201004_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormAK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punkt5_total_outfit_kls', models.IntegerField(blank=True, null=True, verbose_name='Продолжительность всех ПВ кан*час(КЛС)')),
                ('punkt5_total_outfit_rrl', models.IntegerField(blank=True, null=True, verbose_name='Продолжительность всех ПВ кан*час(РРЛ)')),
                ('outfit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formak_outfit', to='objects.Outfit')),
            ],
            options={
                'verbose_name': 'Форма АК',
                'verbose_name_plural': 'Форма АК',
            },
        ),
    ]
