# Generated by Django 2.2.4 on 2020-10-02 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20201001_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificgravityoflengthtypeline',
            name='specific_gravity_of_length',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space', to='analysis.SpecificGravityOfLength'),
        ),
    ]
