# Generated by Django 2.2.4 on 2020-10-13 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20201013_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagecoef',
            name='punkt5_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avg_country_punkt5', to='analysis.Punkt5'),
        ),
        migrations.AlterField(
            model_name='averagecoef',
            name='punkt7_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avg_country_punkt7', to='analysis.Punkt7'),
        ),
    ]
