# Generated by Django 2.2.4 on 2020-10-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20201002_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formanalysis',
            name='average_coefficient',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='formanalysis',
            name='coefficient',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item5',
            name='coefficient',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item5',
            name='downtime',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item5',
            name='length',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='specificgravityoflength',
            name='coefficient',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='specificgravityoflength',
            name='total_length',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='specificgravityoflengthtypeline',
            name='value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
