# Generated by Django 2.2.4 on 2020-10-04 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_formak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punkt5',
            name='event',
        ),
        migrations.AddField(
            model_name='punkt5',
            name='form_ak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='punkt5_form', to='analysis.FormAK'),
        ),
    ]
