# Generated by Django 2.2.4 on 2020-10-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20201013_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagecoef',
            name='punkt5_country',
            field=models.FloatField(blank=True, null=True, verbose_name='Расчет коэф.качества по ЛКХ (п.5)'),
        ),
        migrations.AlterField(
            model_name='averagecoef',
            name='punkt7_country',
            field=models.FloatField(blank=True, null=True, verbose_name='Расчет коэф.качества по ЛКХ (п.7)'),
        ),
    ]
