# Generated by Django 2.2.4 on 2020-10-02 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20201002_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='item5',
            name='id_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.Item5'),
        ),
        migrations.AlterField(
            model_name='formanalysis',
            name='average_coefficient',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='formanalysis',
            name='coefficient',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item5',
            name='downtime',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item5',
            name='length',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item5',
            name='outfit_period_of_time',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='specificgravityoflength',
            name='coefficient',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='specificgravityoflength',
            name='total_length',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='specificgravityoflengthtypeline',
            name='value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
