# Generated by Django 2.2.4 on 2021-02-25 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20201029_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formanalysis',
            name='tv_coefficient',
        ),
    ]
