# Generated by Django 2.2.4 on 2020-10-02 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_auto_20201002_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item5',
            name='id_parent',
        ),
    ]
