# Generated by Django 2.2.4 on 2021-03-29 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0025_auto_20210217_1451'),
        ('analysis', '0006_remove_formanalysis_tv_coefficient'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountChannelsKLSRRL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_channelsKLS', models.IntegerField(blank=True, max_length=255, null=True, verbose_name='КЛС каналы')),
                ('amount_channelsRRL', models.IntegerField(blank=True, max_length=255, null=True, verbose_name='ЦРРЛ каналы')),
                ('ips', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_channelKLSRRL', to='objects.Point')),
                ('object', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_channelKLSRRL', to='objects.Object')),
            ],
            options={
                'verbose_name': 'Количество каналов (КЛС и ЦЦРЛ)',
                'verbose_name_plural': 'Количество каналов (КЛС и ЦЦРЛ)',
            },
        ),
    ]
