# Generated by Django 2.2.4 on 2020-10-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_auto_20201013_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='averagecoef',
            name='coefficient_quality_tv_country',
            field=models.FloatField(blank=True, null=True, verbose_name='Коэффициент качества (ТВ) по Республике'),
        ),
        migrations.AddField(
            model_name='averagecoef',
            name='target_coefficient_country',
            field=models.FloatField(blank=True, null=True, verbose_name='Нормативный коэффициент качества по республике'),
        ),
        migrations.AlterField(
            model_name='averagecoef',
            name='total_coefficient_punkt5',
            field=models.FloatField(blank=True, null=True, verbose_name='Расчет коэф.качества по ЛКХ (п.5)'),
        ),
    ]
