# Generated by Django 2.2.4 on 2020-10-02 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_remove_item5_id_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificgravityoflengthtypeline',
            name='type_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.MainLineType'),
        ),
    ]
