# Generated by Django 2.2.4 on 2021-03-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_amountchannelsklsrrl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountchannelsklsrrl',
            name='amount_channelsKLS',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='КЛС каналы'),
        ),
        migrations.AlterField(
            model_name='amountchannelsklsrrl',
            name='amount_channelsRRL',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ЦРРЛ каналы'),
        ),
    ]
