# Generated by Django 2.2.4 on 2020-10-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_auto_20201013_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='outfit',
        ),
        migrations.RemoveField(
            model_name='country_punkt7',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='country_punkt7',
            name='outfit',
        ),
        migrations.RemoveField(
            model_name='formak',
            name='country',
        ),
        migrations.RemoveField(
            model_name='formak',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='formak',
            name='outfit',
        ),
        migrations.RemoveField(
            model_name='punkt5',
            name='country',
        ),
        migrations.RemoveField(
            model_name='punkt5',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='punkt5',
            name='form_ak',
        ),
        migrations.RemoveField(
            model_name='punkt5',
            name='outfit',
        ),
        migrations.RemoveField(
            model_name='punkt7',
            name='country',
        ),
        migrations.RemoveField(
            model_name='punkt7',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='punkt7',
            name='outfit',
        ),
        migrations.RemoveField(
            model_name='punkt7',
            name='punkt5',
        ),
        migrations.DeleteModel(
            name='AverageCoef',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Country_Punkt7',
        ),
        migrations.DeleteModel(
            name='FormAK',
        ),
        migrations.DeleteModel(
            name='Punkt5',
        ),
        migrations.DeleteModel(
            name='Punkt7',
        ),
    ]
