# Generated by Django 2.2.4 on 2021-04-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_auto_20210331_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='punkt5',
            name='formula_activate',
            field=models.BooleanField(default=True),
        ),
    ]
