# Generated by Django 2.2.4 on 2020-10-02 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_auto_20201002_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formanalysis',
            name='outfit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.Outfit'),
        ),
    ]
