# Generated by Django 2.2.4 on 2021-04-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_punkt5_formula_activate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punkt5',
            name='length_kls',
        ),
        migrations.RemoveField(
            model_name='punkt5',
            name='length_rrl',
        ),
        migrations.RemoveField(
            model_name='punkt5',
            name='length_vls',
        ),
    ]
