# Generated by Django 2.2.4 on 2021-04-05 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_auto_20210405_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punkt7',
            name='corresponding_norm_kls',
        ),
        migrations.RemoveField(
            model_name='punkt7',
            name='corresponding_norm_rrl',
        ),
        migrations.RemoveField(
            model_name='punkt7',
            name='corresponding_norm_vls',
        ),
        migrations.RemoveField(
            model_name='punkt7',
            name='total_number_kls',
        ),
        migrations.RemoveField(
            model_name='punkt7',
            name='total_number_rrl',
        ),
        migrations.RemoveField(
            model_name='punkt7',
            name='total_number_vls',
        ),
    ]
