# Generated by Django 2.2.4 on 2020-10-07 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_auto_20201002_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item5',
            name='outfit_item5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item5', to='analysis.OutfitItem5'),
        ),
        migrations.AlterField(
            model_name='item5',
            name='type_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.MainLineType'),
        ),
        migrations.AlterField(
            model_name='specificgravityoflengthtypeline',
            name='type_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.MainLineType'),
        ),
    ]
