# Generated by Django 2.2.4 on 2020-10-09 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_auto_20201007_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outfititem5',
            options={'verbose_name': 'Предприятия', 'verbose_name_plural': 'Предприятия'},
        ),
        migrations.AlterModelOptions(
            name='specificgravityoflength',
            options={'verbose_name': 'Удельный вес протяженности', 'verbose_name_plural': 'Удельный вес протяженности'},
        ),
        migrations.AlterModelOptions(
            name='specificgravityoflengthtypeline',
            options={'verbose_name': 'Тип линии', 'verbose_name_plural': 'Типы линии'},
        ),
        migrations.AlterField(
            model_name='formanalysis',
            name='average_coefficient',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Средний коэффициент качества'),
        ),
        migrations.AlterField(
            model_name='formanalysis',
            name='coefficient',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Коэффициент качества'),
        ),
        migrations.AlterField(
            model_name='formanalysis',
            name='coefficient_item5',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.OutfitItem5', verbose_name='п.5'),
        ),
        migrations.AlterField(
            model_name='formanalysis',
            name='coefficient_item7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.Item7', verbose_name='п.7'),
        ),
        migrations.AlterField(
            model_name='formanalysis',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='formanalysis',
            name='date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='formanalysis',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='formanalysis',
            name='outfit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.Outfit', verbose_name='Предприятия'),
        ),
        migrations.AlterField(
            model_name='item5',
            name='coefficient',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Коэффициент качества'),
        ),
        migrations.AlterField(
            model_name='item5',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='item5',
            name='date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='item5',
            name='downtime',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Простои'),
        ),
        migrations.AlterField(
            model_name='item5',
            name='length',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Протяженность кан*км'),
        ),
        migrations.AlterField(
            model_name='item5',
            name='outfit_item5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item5', to='analysis.OutfitItem5', verbose_name='Предприятия'),
        ),
        migrations.AlterField(
            model_name='item5',
            name='outfit_period_of_time',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Продолжительность всех ПВ кан*час'),
        ),
        migrations.AlterField(
            model_name='item5',
            name='type_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.MainLineType', verbose_name='Тип линии'),
        ),
        migrations.AlterField(
            model_name='outfititem5',
            name='id_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.OutfitItem5', verbose_name='Республика'),
        ),
        migrations.AlterField(
            model_name='outfititem5',
            name='outfit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.Outfit', verbose_name='Предприятия'),
        ),
        migrations.AlterField(
            model_name='outfititem5',
            name='total_coefficient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysis.SpecificGravityOfLength', verbose_name='Удельный вес протяженности'),
        ),
        migrations.AlterField(
            model_name='specificgravityoflength',
            name='coefficient',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Коэффициент качества'),
        ),
        migrations.AlterField(
            model_name='specificgravityoflength',
            name='total_length',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Общая протяж. кан*км'),
        ),
        migrations.AlterField(
            model_name='specificgravityoflengthtypeline',
            name='specific_gravity_of_length',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space', to='analysis.SpecificGravityOfLength', verbose_name='Удельный вес протяженности'),
        ),
        migrations.AlterField(
            model_name='specificgravityoflengthtypeline',
            name='type_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.MainLineType', verbose_name='Тип линии'),
        ),
        migrations.AlterField(
            model_name='specificgravityoflengthtypeline',
            name='value',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Значение'),
        ),
    ]
