# Generated by Django 2.2.4 on 2021-04-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_auto_20210405_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='punkt5',
            name='formula_activate',
            field=models.BooleanField(default=True),
        ),
    ]
