# Generated by Django 2.2.4 on 2020-10-12 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_auto_20201009_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formanalysis',
            name='coefficient_item7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item7', to='analysis.OutfitItem5', verbose_name='п.7'),
        ),
    ]
