# Generated by Django 2.2.4 on 2020-10-12 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
        ('analysis', '0013_auto_20201012_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item7',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='item7',
            name='date_to',
        ),
        migrations.AddField(
            model_name='item7',
            name='coefficient',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Коэффициент качества'),
        ),
        migrations.AddField(
            model_name='item7',
            name='corresponding_norm',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Соответствующих норме'),
        ),
        migrations.AddField(
            model_name='item7',
            name='match_percentage',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Процент соответствия'),
        ),
        migrations.AddField(
            model_name='item7',
            name='outfit_item5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item7', to='analysis.OutfitItem5', verbose_name='Предприятия'),
        ),
        migrations.AddField(
            model_name='item7',
            name='total_object',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Общее количество линейных трактов'),
        ),
        migrations.AddField(
            model_name='item7',
            name='type_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.MainLineType', verbose_name='Тип линии'),
        ),
        migrations.AlterField(
            model_name='formanalysis',
            name='coefficient_item7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_item7', to='analysis.OutfitItem5', verbose_name='п.7'),
        ),
    ]
