# Generated by Django 2.2.4 on 2021-04-14 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0028_auto_20210405_1515'),
        ('analysis', '0013_punkt5_formula_activate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LayingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Form61',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_length', models.FloatField(default=0, verbose_name='Общ. прот лин')),
                ('cable_length', models.FloatField(default=0, verbose_name='Общ. прот каб')),
                ('date_cabling', models.DateField(auto_now_add=True)),
                ('cable_laying_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.LayingMethod')),
                ('outfit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.Outfit')),
                ('point1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form61_point1', to='objects.Point')),
                ('point2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form61_point2', to='objects.Point')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_length', models.FloatField(default=0, verbose_name='Общ. прот лин')),
                ('cable_length', models.FloatField(default=0, verbose_name='Общ. прот каб')),
                ('nodes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='analysis.Connection')),
                ('point', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.Point')),
            ],
        ),
    ]
