# Generated by Django 2.2.4 on 2021-04-13 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0028_auto_20210405_1515'),
        ('analysis', '0013_punkt5_formula_activate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodLaying',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Способ прокладки',
                'verbose_name_plural': 'Способы прокладки',
            },
        ),
        migrations.CreateModel(
            name='TypeCable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип кабеля',
                'verbose_name_plural': 'Тип кабеля',
            },
        ),
        migrations.CreateModel(
            name='TypeConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип связи',
                'verbose_name_plural': 'Тип связи',
            },
        ),
        migrations.CreateModel(
            name='Form61RRL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_length_line', models.FloatField(blank=True, default=0, null=True, verbose_name='Общая протяженность линии РРЛ')),
                ('type_equipment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип аппаратуры')),
                ('src', models.ImageField(blank=True, upload_to='files/', verbose_name='Схема')),
                ('outfit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form61_RRL_out', to='objects.Outfit', verbose_name='Предприятия')),
                ('point1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form61_RRL_point', to='objects.Point', verbose_name='ИП от')),
                ('point2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form61_RRL_point2', to='objects.Point', verbose_name='ИП до')),
            ],
            options={
                'verbose_name': 'Форма 61 (РРЛ)',
                'verbose_name_plural': 'Форма 61 (РРЛ)',
            },
        ),
        migrations.CreateModel(
            name='Form61KLS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_length_line', models.FloatField(blank=True, default=0, null=True, verbose_name='Общая протяженность линии КЛС')),
                ('total_length_cable', models.FloatField(blank=True, default=0, null=True, verbose_name='Общая протяженность кабеля КЛС')),
                ('above_ground', models.FloatField(blank=True, default=0, null=True, verbose_name='Проложено над землей')),
                ('under_ground', models.FloatField(blank=True, default=0, null=True, verbose_name='Проложено под землей')),
                ('year_of_laying', models.CharField(blank=True, max_length=255, null=True, verbose_name='Год прокладки')),
                ('src', models.ImageField(blank=True, upload_to='files/', verbose_name='Схема')),
                ('laying_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.MethodLaying', verbose_name='Способ прокладки')),
                ('outfit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form61_KLS_out', to='objects.Outfit', verbose_name='Предприятия')),
                ('point1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form61_KLS_point', to='objects.Point', verbose_name='ИП от')),
                ('point2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form61_KLS_point2', to='objects.Point', verbose_name='ИП до')),
                ('type_cable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.TypeCable', verbose_name='Тип кабеля')),
                ('type_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form61_KLS_connection', to='analysis.TypeConnection', verbose_name='Тип Связи')),
            ],
            options={
                'verbose_name': 'Форма 61 (ВОЛС)',
                'verbose_name_plural': 'Форма 61 (ВОЛС)',
            },
        ),
    ]
