# Generated by Django 2.2.4 on 2021-04-14 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_communicationtype_connection_form61_layingmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='cable_length',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='line_length',
        ),
    ]
