# Generated by Django 2.2.4 on 2020-10-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_auto_20201012_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='item7',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Начало'),
        ),
        migrations.AddField(
            model_name='item7',
            name='date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Конец'),
        ),
    ]
