# Generated by Django 2.2.4 on 2021-04-18 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_form61kls_form61rrl_methodlaying_typecable_typeconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='form61rrl',
            name='type_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form61_RRL_connection', to='analysis.TypeConnection', verbose_name='Тип Связи'),
        ),
    ]
