# Generated by Django 2.2.4 on 2021-04-14 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_auto_20210414_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form61',
            old_name='point1',
            new_name='point',
        ),
        migrations.RemoveField(
            model_name='form61',
            name='point2',
        ),
        migrations.AddField(
            model_name='form61',
            name='nodes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='analysis.Form61'),
        ),
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
