# Generated by Django 2.2.4 on 2020-10-13 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_auto_20201012_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item5',
            name='outfit_item5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item5', to='analysis.OutfitItem5', verbose_name='Предприятия'),
        ),
        migrations.AlterField(
            model_name='item7',
            name='outfit_item5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item7', to='analysis.OutfitItem5', verbose_name='Предприятия'),
        ),
    ]
