# Generated by Django 2.2.4 on 2020-10-13 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_auto_20201013_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formanalysis',
            name='coefficient_item5',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_item5', to='analysis.OutfitItem5', verbose_name='п.5'),
        ),
        migrations.AlterField(
            model_name='formanalysis',
            name='coefficient_item7',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_item7', to='analysis.OutfitItem5', verbose_name='п.7'),
        ),
    ]
