# Generated by Django 2.2.4 on 2021-04-14 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_auto_20210414_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form61',
            name='point',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.Point'),
        ),
    ]
