# Generated by Django 2.2.4 on 2020-10-14 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0017_auto_20201013_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfititem5',
            name='id_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_out', to='analysis.OutfitItem5', verbose_name='Республика'),
        ),
    ]
