# Generated by Django 2.2.4 on 2020-10-14 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0018_auto_20201014_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='item5',
            name='type_line_value',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_line_value', to='analysis.SpecificGravityOfLengthTypeLine'),
        ),
    ]
