# Generated by Django 2.2.4 on 2021-04-15 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0028_auto_20210405_1515'),
        ('analysis', '0018_auto_20210414_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form61',
            name='outfit',
        ),
        migrations.RemoveField(
            model_name='form61',
            name='point',
        ),
        migrations.AddField(
            model_name='form61',
            name='outfits',
            field=models.ManyToManyField(blank=True, null=True, related_name='form61', to='objects.Outfit'),
        ),
        migrations.AddField(
            model_name='form61',
            name='point1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point1_form61', to='objects.Point'),
        ),
        migrations.AddField(
            model_name='form61',
            name='point2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point2_form61', to='objects.Point'),
        ),
    ]
