# Generated by Django 2.2.4 on 2021-04-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0019_auto_20210415_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='form61',
            name='cable_length_out1',
            field=models.FloatField(default=0, verbose_name='Общ. прот каб'),
        ),
        migrations.AddField(
            model_name='form61',
            name='cable_length_out2',
            field=models.FloatField(default=0, verbose_name='Общ. прот каб'),
        ),
        migrations.AddField(
            model_name='form61',
            name='line_length_out1',
            field=models.FloatField(default=0, verbose_name='Общ. прот лин'),
        ),
        migrations.AddField(
            model_name='form61',
            name='line_length_out2',
            field=models.FloatField(default=0, verbose_name='Общ. прот лин'),
        ),
    ]
