# Generated by Django 2.2.4 on 2020-10-14 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0019_item5_type_line_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specificgravityoflength',
            name='id_parent',
        ),
        migrations.AddField(
            model_name='item7',
            name='type_line_value',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_line_value7', to='analysis.SpecificGravityOfLengthTypeLine'),
        ),
    ]
