# Generated by Django 2.2.4 on 2020-10-14 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0020_auto_20201014_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificgravityoflength',
            name='id_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.SpecificGravityOfLength'),
        ),
    ]
