# Generated by Django 2.2.4 on 2020-10-15 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0021_specificgravityoflength_id_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item5',
            name='type_line_value',
        ),
        migrations.RemoveField(
            model_name='item7',
            name='type_line_value',
        ),
        migrations.AddField(
            model_name='specificgravityoflengthtypeline',
            name='type_line_value',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_line_value', to='analysis.Item5'),
        ),
        migrations.AddField(
            model_name='specificgravityoflengthtypeline',
            name='type_line_value7',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_line_value7', to='analysis.Item7'),
        ),
    ]
