# Generated by Django 2.2.4 on 2021-04-15 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0028_auto_20210405_1515'),
        ('analysis', '0021_auto_20210415_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form61',
            name='cable_length',
        ),
        migrations.RemoveField(
            model_name='form61',
            name='cable_length_out1',
        ),
        migrations.RemoveField(
            model_name='form61',
            name='cable_length_out2',
        ),
        migrations.RemoveField(
            model_name='form61',
            name='line_length',
        ),
        migrations.RemoveField(
            model_name='form61',
            name='line_length_out1',
        ),
        migrations.RemoveField(
            model_name='form61',
            name='line_length_out2',
        ),
        migrations.CreateModel(
            name='Length',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_length', models.FloatField(default=0, verbose_name='Общ. прот лин')),
                ('cable_length', models.FloatField(default=0, verbose_name='Общ. прот каб')),
                ('main_length', models.BooleanField(default=True)),
                ('outfits', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='length', to='objects.Outfit')),
            ],
        ),
        migrations.AddField(
            model_name='form61',
            name='lengths',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form56', to='analysis.Length'),
        ),
    ]
