# Generated by Django 2.2.4 on 2021-04-15 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0028_auto_20210405_1515'),
        ('analysis', '0022_auto_20210415_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='analysis.Station')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.Point')),
            ],
        ),
    ]
