# Generated by Django 2.2.4 on 2020-10-15 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
        ('analysis', '0022_auto_20201015_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Предприятия',
                'verbose_name_plural': 'Предприятия',
            },
        ),
        migrations.CreateModel(
            name='TotalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_length', models.FloatField(blank=True, default=0, null=True, verbose_name='Общая протяж. кан*км')),
                ('coefficient', models.FloatField(blank=True, default=0, null=True, verbose_name='Коэффициент качества')),
                ('id_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.TotalData')),
                ('outfit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='out_item', to='analysis.OutfitItem')),
            ],
            options={
                'verbose_name': 'Удельный вес протяженности',
                'verbose_name_plural': 'Удельный вес протяженности',
            },
        ),
        migrations.CreateModel(
            name='TypeLineValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, default=0, null=True, verbose_name='Значение')),
                ('total_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_lines', to='analysis.TotalData', verbose_name='Удельный вес протяженности')),
                ('type_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.MainLineType', verbose_name='Тип линии')),
            ],
            options={
                'verbose_name': 'Тип линии',
                'verbose_name_plural': 'Типы линии',
            },
        ),
        migrations.RemoveField(
            model_name='specificgravityoflength',
            name='id_parent',
        ),
        migrations.RemoveField(
            model_name='specificgravityoflengthtypeline',
            name='specific_gravity_of_length',
        ),
        migrations.RemoveField(
            model_name='specificgravityoflengthtypeline',
            name='type_line',
        ),
        migrations.RemoveField(
            model_name='specificgravityoflengthtypeline',
            name='type_line_value',
        ),
        migrations.RemoveField(
            model_name='specificgravityoflengthtypeline',
            name='type_line_value7',
        ),
        migrations.RenameField(
            model_name='item7',
            old_name='match_percentage',
            new_name='percentage_compliance',
        ),
        migrations.RemoveField(
            model_name='formanalysis',
            name='coefficient_item5',
        ),
        migrations.RemoveField(
            model_name='formanalysis',
            name='coefficient_item7',
        ),
        migrations.RemoveField(
            model_name='item5',
            name='outfit_item5',
        ),
        migrations.RemoveField(
            model_name='item7',
            name='outfit_item5',
        ),
        migrations.AddField(
            model_name='formanalysis',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='OutfitItem5',
        ),
        migrations.DeleteModel(
            name='SpecificGravityOfLength',
        ),
        migrations.DeleteModel(
            name='SpecificGravityOfLengthTypeLine',
        ),
        migrations.AddField(
            model_name='outfititem',
            name='analysis_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outfit_item', to='analysis.FormAnalysis', verbose_name='Форма анализа'),
        ),
        migrations.AddField(
            model_name='outfititem',
            name='id_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_out', to='analysis.OutfitItem', verbose_name='Республика'),
        ),
        migrations.AddField(
            model_name='outfititem',
            name='outfit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.Outfit', verbose_name='Предприятия'),
        ),
        migrations.AddField(
            model_name='item5',
            name='outfit_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item5', to='analysis.OutfitItem', verbose_name='Предприятия'),
        ),
        migrations.AddField(
            model_name='item7',
            name='outfit_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item7', to='analysis.OutfitItem', verbose_name='Предприятия'),
        ),
    ]
