# Generated by Django 2.2.4 on 2021-04-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0023_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form61',
            name='parent',
        ),
    ]
