# Generated by Django 2.2.4 on 2020-10-16 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0023_auto_20201015_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfititem',
            name='analysis_form',
        ),
        migrations.AddField(
            model_name='outfititem',
            name='analysis_form_item5',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='out_item5', to='analysis.FormAnalysis', verbose_name='Форма анализа'),
        ),
        migrations.AddField(
            model_name='outfititem',
            name='analysis_form_item7',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='out_item7', to='analysis.FormAnalysis', verbose_name='Форма анализа'),
        ),
    ]
