# Generated by Django 2.2.4 on 2021-04-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0024_remove_form61_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='length',
            old_name='outfits',
            new_name='outfit',
        ),
    ]
