# Generated by Django 2.2.4 on 2021-04-15 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0025_auto_20210415_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form61',
            name='lengths',
        ),
        migrations.AddField(
            model_name='length',
            name='form61',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lengths', to='analysis.Form61'),
        ),
    ]
