# Generated by Django 2.2.4 on 2021-04-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0027_auto_20210416_1231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunicationType',
        ),
        migrations.RemoveField(
            model_name='length',
            name='form61',
        ),
        migrations.RemoveField(
            model_name='length',
            name='outfit',
        ),
        migrations.RemoveField(
            model_name='station',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='station',
            name='point',
        ),
        migrations.DeleteModel(
            name='Form61',
        ),
        migrations.DeleteModel(
            name='LayingMethod',
        ),
        migrations.DeleteModel(
            name='Length',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
