# Generated by Django 2.2.4 on 2021-04-23 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_form61rrl_type_connection'),
        ('analysis', '0028_auto_20210423_1203'),
    ]

    operations = [
    ]
