# Generated by Django 2.2.4 on 2021-04-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0029_merge_20210423_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form61kls',
            name='laying_method',
        ),
        migrations.AddField(
            model_name='form61kls',
            name='laying_method',
            field=models.ManyToManyField(related_name='form61_methods', to='analysis.MethodLaying', verbose_name='Способ прокладки'),
        ),
    ]
