# Generated by Django 2.2.4 on 2021-05-04 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0031_methodlaying_is_read_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип аппаратуры',
                'verbose_name_plural': 'Тип аппаратуры',
            },
        ),
        migrations.AlterField(
            model_name='form61rrl',
            name='type_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_equipment_rrl', to='analysis.TypeEquipment', verbose_name='Тип аппаратуры'),
        ),
    ]
