# Generated by Django 2.2.4 on 2021-05-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0032_auto_20210504_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form61rrl',
            old_name='type_equipment',
            new_name='type_equipment_rrl',
        ),
        migrations.RemoveField(
            model_name='form61rrl',
            name='src',
        ),
    ]
