# Generated by Django 2.2.4 on 2021-05-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0034_auto_20210525_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form61rrl',
            name='number_trunk',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество стволов'),
        ),
        migrations.DeleteModel(
            name='NumberTrunk',
        ),
    ]
