# Generated by Django 2.2.4 on 2021-05-26 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0035_auto_20210525_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='form61rrl',
            name='year_of_building',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Год постройки'),
        ),
        migrations.CreateModel(
            name='OrderRRLPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.FileField(blank=True, upload_to='files/', verbose_name='Схема')),
                ('form61_rrl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form61_rrl_order_photo', to='analysis.Form61RRL', verbose_name='Распоряжение')),
            ],
        ),
        migrations.CreateModel(
            name='OrderKLSPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.FileField(blank=True, upload_to='files/', verbose_name='Схема')),
                ('form61_kls', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form61_kls_order_photo', to='analysis.Form61KLS', verbose_name='Распоряжение')),
            ],
        ),
    ]
