# Generated by Django 2.2.4 on 2021-05-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0036_auto_20210526_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form61kls',
            name='src',
        ),
    ]
