# Generated by Django 2.2.4 on 2021-07-21 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0037_remove_form61kls_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountchannelsklsrrl',
            name='ips',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_channel', to='objects.Point'),
        ),
    ]
