# Generated by Django 2.2.4 on 2021-08-18 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('customer', '0001_initial'),
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_circuit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер канала')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('num_order', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('first', models.BooleanField(default=True, verbose_name='Используется/Не используется')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_modified', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circ_cat', to='objects.Category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circ_cust', to='customer.Customer')),
                ('id_object', models.ManyToManyField(blank=True, related_name='circ_obj', to='objects.Object')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circuit_object_parent', to='objects.Object')),
                ('point1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circ_ip1', to='objects.Point')),
                ('point2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circ_ip2', to='objects.Point')),
            ],
            options={
                'verbose_name': 'Канал для Формы 5.3',
                'verbose_name_plural': 'Каналы для Формы 5.3',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CircuitTransit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_trassa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circuit_transit', to='objects.Transit')),
                ('trassa', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='transits', to='circuits.Circuit')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCircuit',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('num_circuit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер канала')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('num_order', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('first', models.BooleanField(default=True, verbose_name='Используется/Не используется')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('is_modified', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='objects.Category')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.Profile')),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer.Customer')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history_circuit_log', to='circuits.Circuit')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='objects.Object')),
                ('point1', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='objects.Point')),
                ('point2', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='objects.Point')),
                ('trassa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='circuits.CircuitTransit')),
            ],
            options={
                'verbose_name': 'historical Канал для Формы 5.3',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='circuit',
            name='trassa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circuits', to='circuits.CircuitTransit'),
        ),
    ]
