# Generated by Django 2.2.4 on 2020-08-20 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mode',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='speed',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subsroutes',
            name='route',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='typecom',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
