# Generated by Django 2.2.4 on 2020-06-08 09:08

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0001_initial_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='transit',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='cir_transit_obj1', to='circuits.Circuit'),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='transit2',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='cir_transit_obj2', to='circuits.Circuit'),
        ),
    ]
