# Generated by Django 2.2.4 on 2020-06-01 07:54

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
        ('circuits', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='TypeCom',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='destination1',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='destination2',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='id_transit1',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='id_transit2',
        ),
        migrations.AddField(
            model_name='circuit',
            name='point1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circ_ip1', to='objects.Point'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='point2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circ_ip2', to='objects.Point'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='transit',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='cir_transit_obj1', to='objects.Object'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='transit2',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='cir_transit_obj2', to='objects.Object'),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер'),
        ),
    ]
