# Generated by Django 2.2.4 on 2020-09-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circuit',
            options={'ordering': ('id',), 'verbose_name': 'Канал для Формы 5.3', 'verbose_name_plural': 'Каналы для Формы 5.3'},
        ),
        migrations.AlterField(
            model_name='circuit',
            name='first',
            field=models.BooleanField(default=False, verbose_name='Используется/Не используется'),
        ),
    ]
