# Generated by Django 2.2.4 on 2021-08-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuittransit',
            name='reverse_circuit',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
