# Generated by Django 2.2.4 on 2020-10-13 13:51

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('circuits', '0001_initial'),
        ('objects', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circ_cat', to='objects.Category'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circ_cust', to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='final_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circ_final_dest', to='objects.Point'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='id_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circ_obj', to='objects.Object'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='id_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='circuits.Circuit'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='in_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circ_in', to='objects.InOut'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circ_measure', to='circuits.Measure'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circ_mode', to='circuits.Mode'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='point1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circ_ip1', to='objects.Point'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='point2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circ_ip2', to='objects.Point'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='transit',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='cir_transit_obj1', to='circuits.Circuit'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='transit2',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='cir_transit_obj2', to='circuits.Circuit'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='type_com',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circ_type_com', to='circuits.TypeCom'),
        ),
        migrations.AddField(
            model_name='bypass',
            name='id_bypass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_bypass', to='circuits.Circuit'),
        ),
        migrations.AddField(
            model_name='bypass',
            name='id_main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bypass_id_main', to='circuits.Circuit'),
        ),
        migrations.AddField(
            model_name='assignpart',
            name='id_object_main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_obj_main', to='objects.Object'),
        ),
        migrations.AddField(
            model_name='assignpart',
            name='id_object_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_obj_part', to='objects.Object'),
        ),
    ]
