# Generated by Django 2.2.4 on 2020-06-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='adding',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='speed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
