# Generated by Django 2.2.4 on 2021-08-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0002_circuittransit_reverse_circuit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circuittransit',
            old_name='reverse_circuit',
            new_name='reverse_circuits',
        ),
    ]
