# Generated by Django 2.2.4 on 2020-11-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_auto_20201111_1159'),
        ('circuits', '0002_historicalcircuit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcircuit',
            name='id_object',
        ),
        migrations.AlterField(
            model_name='circuit',
            name='first',
            field=models.BooleanField(default=True, verbose_name='Используется/Не используется'),
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='id_object',
        ),
        migrations.AddField(
            model_name='circuit',
            name='id_object',
            field=models.ManyToManyField(blank=True, related_name='circ_obj', to='objects.Object'),
        ),
        migrations.AlterField(
            model_name='historicalcircuit',
            name='first',
            field=models.BooleanField(default=True, verbose_name='Используется/Не используется'),
        ),
    ]
