# Generated by Django 2.2.4 on 2020-08-21 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0002_auto_20200820_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circ_cat', to='objects.Category'),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circ_cust', to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='id_subst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circ_subst', to='circuits.SubsRoutes'),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='in_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circ_in', to='objects.InOut'),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circ_measure', to='circuits.Measure'),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circ_mode', to='circuits.Mode'),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='point1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circ_ip1', to='objects.Point'),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='point2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circ_ip2', to='objects.Point'),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='type_com',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circ_type_com', to='circuits.TypeCom'),
        ),
    ]
