# Generated by Django 2.2.4 on 2020-11-11 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_auto_20201111_1159'),
        ('circuits', '0003_auto_20201111_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcircuit',
            name='id_object',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='objects.Object'),
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='id_object',
        ),
        migrations.AddField(
            model_name='circuit',
            name='id_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circ_obj', to='objects.Object'),
        ),
    ]
