# Generated by Django 2.2.4 on 2020-06-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0004_auto_20200602_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='first',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
