# Generated by Django 2.2.4 on 2020-11-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0005_auto_20201111_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='id_object',
            field=models.ManyToManyField(blank=True, related_name='circ_obj', to='objects.Object'),
        ),
    ]
