# Generated by Django 2.2.4 on 2020-06-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0006_auto_20200602_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
