# Generated by Django 2.2.4 on 2020-11-24 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0010_auto_20201124_1104'),
        ('circuits', '0006_auto_20201111_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuit',
            name='id_parent',
        ),
        migrations.RemoveField(
            model_name='historicalcircuit',
            name='id_parent',
        ),
        migrations.AddField(
            model_name='circuit',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circuit_object_parent', to='objects.Object'),
        ),
        migrations.AddField(
            model_name='historicalcircuit',
            name='object',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='objects.Object'),
        ),
    ]
