# Generated by Django 2.2.4 on 2021-01-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0007_auto_20201124_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bypass',
            name='id_bypass',
        ),
        migrations.RemoveField(
            model_name='bypass',
            name='id_main',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='adding',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='date_order',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='final_destination',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='in_out',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='number',
        ),
        migrations.RemoveField(
            model_name='historicalcircuit',
            name='adding',
        ),
        migrations.RemoveField(
            model_name='historicalcircuit',
            name='date_order',
        ),
        migrations.RemoveField(
            model_name='historicalcircuit',
            name='final_destination',
        ),
        migrations.RemoveField(
            model_name='historicalcircuit',
            name='in_out',
        ),
        migrations.RemoveField(
            model_name='historicalcircuit',
            name='number',
        ),
        migrations.DeleteModel(
            name='AssignPart',
        ),
        migrations.DeleteModel(
            name='Bypass',
        ),
    ]
