# Generated by Django 2.2.4 on 2021-01-19 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0008_auto_20210119_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuit',
            name='num_arenda',
        ),
        migrations.RemoveField(
            model_name='historicalcircuit',
            name='num_arenda',
        ),
    ]
