# Generated by Django 2.2.4 on 2021-05-17 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0011_auto_20210504_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuittransit',
            name='obj_trassa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circuit_transit', to='objects.Transit'),
        ),
    ]
