# Generated by Django 2.2.4 on 2021-06-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0012_auto_20210517_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuit',
            name='transit',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='transit2',
        ),
    ]
