# Generated by Django 2.2.4 on 2021-06-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0013_auto_20210601_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='is_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcircuit',
            name='is_modified',
            field=models.BooleanField(default=False),
        ),
    ]
