# Generated by Django 2.2.4 on 2021-08-18 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('objects', '0001_initial'),
        ('secondary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceNumsBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=500, null=True, verbose_name='Район')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='Код')),
                ('main_num', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Главный номер')),
                ('first_redirection', models.CharField(blank=True, max_length=5500, null=True, verbose_name='Первая переадресация')),
                ('second_redirection', models.CharField(blank=True, max_length=5500, null=True, verbose_name='Вторая переадресация')),
                ('third_redirection', models.CharField(blank=True, max_length=5500, null=True, verbose_name='Третья переадресация')),
                ('comments', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Примечание')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile', verbose_name='ФИО диспетчера')),
                ('outfit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambul_out', to='objects.Outfit')),
            ],
            options={
                'verbose_name': 'База тел.номеров 118',
                'verbose_name_plural': 'База тел.номеров 118',
                'ordering': ('id',),
                'get_latest_by': 'id',
            },
        ),
    ]
