# Generated by Django 2.2.4 on 2021-04-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeStantion',
            new_name='TypeStation',
        ),
        migrations.RemoveField(
            model_name='secondarybase',
            name='active_value_signal_terminal',
        ),
        migrations.RemoveField(
            model_name='secondarybase',
            name='installed_value_signal_terminal',
        ),
        migrations.AddField(
            model_name='secondarybase',
            name='GAS_return',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Возврат в ГАС'),
        ),
    ]
