# Generated by Django 2.2.4 on 2021-08-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0002_ambulancenumsbase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulancenumsbase',
            name='code',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Код'),
        ),
    ]
