# Generated by Django 2.2.4 on 2021-04-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0002_auto_20210402_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondarybase',
            name='administrative_name',
        ),
        migrations.AlterField(
            model_name='secondarybase',
            name='active_numbering',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Задействованная нумерация'),
        ),
    ]
