# Generated by Django 2.2.4 on 2021-09-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0003_auto_20210818_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondarybase',
            name='amount_of_numbers',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество выделенных номеров'),
        ),
        migrations.AddField(
            model_name='secondarybase',
            name='inner_zone_code',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Внутризон. Код АВ'),
        ),
        migrations.AddField(
            model_name='secondarybase',
            name='zone_code',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Зон код АВ'),
        ),
        migrations.AlterField(
            model_name='secondarybase',
            name='KT_numbering',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Нумерация КТ'),
        ),
    ]
