# Generated by Django 2.2.4 on 2021-04-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0003_auto_20210402_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondarybase',
            name='active_value',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Задействованная емкость'),
        ),
        migrations.AlterField(
            model_name='secondarybase',
            name='free_numbering',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Свободная нумерация'),
        ),
        migrations.AlterField(
            model_name='secondarybase',
            name='installed_value',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Монтированная емкость'),
        ),
    ]
