# Generated by Django 2.2.4 on 2021-06-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0004_auto_20210419_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondarybase',
            name='administrative_division',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='secondarybase',
            name='comments',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Примечание'),
        ),
    ]
