# Generated by Django 2.2.4 on 2021-09-02 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0004_auto_20210902_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondarybase',
            name='GAS_return',
        ),
    ]
