# Generated by Django 2.2.4 on 2021-06-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0005_auto_20210607_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondarybase',
            name='GAS_numbering',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Выделенная ГАС нумерация'),
        ),
        migrations.AlterField(
            model_name='secondarybase',
            name='GAS_return',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Возврат в ГАС'),
        ),
        migrations.AlterField(
            model_name='secondarybase',
            name='KT_numbering',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Нумерация КТ'),
        ),
        migrations.AlterField(
            model_name='secondarybase',
            name='active_numbering',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Задействованная нумерация'),
        ),
        migrations.AlterField(
            model_name='secondarybase',
            name='active_value',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Задействованная емкость'),
        ),
        migrations.AlterField(
            model_name='secondarybase',
            name='administrative_division',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='secondarybase',
            name='free_numbering',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Свободная нумерация'),
        ),
        migrations.AlterField(
            model_name='secondarybase',
            name='installed_value',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Монтированная емкость'),
        ),
    ]
