# Generated by Django 2.2.4 on 2020-09-17 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0006_auto_20200917_1233'),
        ('customer', '0002_auto_20200914_1522'),
        ('circuits', '0002_auto_20200914_1522'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Примечание',
                'verbose_name_plural': 'Примечание',
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=255, verbose_name='Индекс')),
                ('name', models.CharField(max_length=255, verbose_name='Название индекса')),
            ],
            options={
                'verbose_name': 'Индекс события',
                'verbose_name_plural': 'Индекс события',
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Причины',
                'verbose_name_plural': 'Причины',
            },
        ),
        migrations.CreateModel(
            name='TypeOfJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Виды журнала',
                'verbose_name_plural': 'Вид журнала',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(blank=True, null=True, verbose_name='От')),
                ('date_to', models.DateTimeField(blank=True, null=True, verbose_name='До')),
                ('date_calls', models.DateTimeField(blank=True, null=True, verbose_name='Время звонка')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='Дата создания')),
                ('comments1', models.CharField(blank=True, max_length=500, null=True, verbose_name='Примечание1')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название')),
                ('callsorevent', models.BooleanField(default=True)),
                ('period_of_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Сумма часов, за которое устранили аварию')),
                ('circuit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_cir', to='circuits.Circuit', verbose_name='Каналы')),
                ('contact_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.OutfitWorker', verbose_name='Передал (ФИО)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile', verbose_name='ФИО диспетчера')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='Арендаторы')),
                ('id_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_id_parent', to='dispatching.Event')),
                ('index1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_index1', to='dispatching.Index', verbose_name='Индекс1')),
                ('ips', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_ips', to='objects.IP', verbose_name='ИПы')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_obj', to='objects.Object', verbose_name='КО')),
                ('point1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point1_event', to='objects.Point', verbose_name='Ип от')),
                ('point2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point2_event', to='objects.Point', verbose_name='Ип до')),
                ('previous', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_previous', to='dispatching.Event')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispatching.Reason', verbose_name='Причины')),
                ('responsible_outfit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_outfit', to='objects.Outfit', verbose_name='Ответственный')),
                ('send_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_send_outfit', to='objects.Outfit', verbose_name='Передал (предприятие)')),
                ('type_journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatching.TypeOfJournal', verbose_name='Вид журнала')),
            ],
            options={
                'verbose_name': 'Журнал событий',
                'verbose_name_plural': 'Журнал событий',
                'ordering': ('id',),
                'get_latest_by': 'id',
            },
        ),
    ]
