# Generated by Django 2.2.4 on 2020-12-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='period_of_time',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='period_of_time',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
