# Generated by Django 2.2.4 on 2020-09-21 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='period_of_time',
        ),
    ]
