# Generated by Django 2.2.4 on 2020-09-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='changed_field',
            field=models.CharField(blank=True, max_length=100500, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='changed_field',
            field=models.CharField(blank=True, max_length=100500, null=True, verbose_name='Название'),
        ),
    ]
