# Generated by Django 2.2.4 on 2020-09-08 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('id',), 'verbose_name': 'Журнал событий', 'verbose_name_plural': 'Журнал событий'},
        ),
    ]
