# Generated by Django 2.2.4 on 2020-10-13 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('circuits', '0002_auto_20201013_1351'),
        ('accounts', '0001_initial'),
        ('dispatching', '0001_initial'),
        ('objects', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalevent',
            name='contact_name',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='objects.OutfitWorker', verbose_name='Передал (ФИО)'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.Profile', verbose_name='ФИО диспетчера'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer.Customer', verbose_name='Арендаторы'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history_log', to='dispatching.Event'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='id_parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dispatching.Event'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='index1',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dispatching.Index', verbose_name='Индекс1'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='ips',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='objects.IP', verbose_name='ИПы'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='object',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='objects.Object', verbose_name='КО'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='point1',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='objects.Point', verbose_name='Ип от'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='point2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='objects.Point', verbose_name='Ип до'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='previous',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dispatching.Event'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='reason',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dispatching.Reason', verbose_name='Причины'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='responsible_outfit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='objects.Outfit', verbose_name='Ответственный'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='send_from',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='objects.Outfit', verbose_name='Передал (предприятие)'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='type_journal',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dispatching.TypeOfJournal', verbose_name='Вид журнала'),
        ),
        migrations.AddField(
            model_name='event',
            name='circuit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_cir', to='circuits.Circuit', verbose_name='Каналы'),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.OutfitWorker', verbose_name='Передал (ФИО)'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile', verbose_name='ФИО диспетчера'),
        ),
        migrations.AddField(
            model_name='event',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='Арендаторы'),
        ),
        migrations.AddField(
            model_name='event',
            name='id_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_id_parent', to='dispatching.Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='index1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_index1', to='dispatching.Index', verbose_name='Индекс1'),
        ),
        migrations.AddField(
            model_name='event',
            name='ips',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_ips', to='objects.IP', verbose_name='ИПы'),
        ),
        migrations.AddField(
            model_name='event',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_obj', to='objects.Object', verbose_name='КО'),
        ),
        migrations.AddField(
            model_name='event',
            name='point1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point1_event', to='objects.Point', verbose_name='Ип от'),
        ),
        migrations.AddField(
            model_name='event',
            name='point2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point2_event', to='objects.Point', verbose_name='Ип до'),
        ),
        migrations.AddField(
            model_name='event',
            name='previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_previous', to='dispatching.Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispatching.Reason', verbose_name='Причины'),
        ),
        migrations.AddField(
            model_name='event',
            name='responsible_outfit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_outfit', to='objects.Outfit', verbose_name='Ответственный'),
        ),
        migrations.AddField(
            model_name='event',
            name='send_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_send_outfit', to='objects.Outfit', verbose_name='Передал (предприятие)'),
        ),
        migrations.AddField(
            model_name='event',
            name='type_journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatching.TypeOfJournal', verbose_name='Вид журнала'),
        ),
    ]
