# Generated by Django 2.2.4 on 2020-09-28 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='updated_date',
        ),
    ]
