# Generated by Django 2.2.4 on 2020-08-17 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0002_auto_20200817_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contact_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.OutfitWorker', verbose_name='Передал (ФИО)'),
        ),
    ]
