# Generated by Django 2.2.4 on 2020-09-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0002_auto_20200924_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='period_of_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='period_of_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
