# Generated by Django 2.2.4 on 2021-09-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_auto_20210824_2320'),
        ('dispatching', '0002_auto_20210824_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='object_reports',
            field=models.ManyToManyField(blank=True, null=True, related_name='obj_reports', to='objects.Object'),
        ),
    ]
