# Generated by Django 2.2.4 on 2021-01-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0002_auto_20201207_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='is_read_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reason',
            name='is_read_only',
            field=models.BooleanField(default=False),
        ),
    ]
