# Generated by Django 2.2.4 on 2020-09-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0002_auto_20200908_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='comments2',
        ),
    ]
