# Generated by Django 2.2.4 on 2020-09-28 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0002_auto_20200928_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='updated_by',
        ),
    ]
