# Generated by Django 2.2.4 on 2021-02-09 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0003_auto_20210119_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ips',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_ips', to='objects.Point', verbose_name='ИПы'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='ips',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='objects.Point', verbose_name='ИПы'),
        ),
    ]
