# Generated by Django 2.2.4 on 2020-09-10 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0003_remove_event_comments2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'get_latest_by': 'id', 'ordering': ('id',), 'verbose_name': 'Журнал событий', 'verbose_name_plural': 'Журнал событий'},
        ),
    ]
