# Generated by Django 2.2.4 on 2020-09-29 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0003_auto_20200928_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalevent',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
