# Generated by Django 2.2.4 on 2021-09-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0003_event_object_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='object_reports',
            field=models.ManyToManyField(blank=True, related_name='obj_reports', to='objects.Object'),
        ),
    ]
