# Generated by Django 2.2.4 on 2020-06-02 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0003_request_subdepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name='shutdownlog',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatching.Region', verbose_name='Регион'),
        ),
    ]
