# Generated by Django 2.2.4 on 2020-09-10 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0003_remove_event_comments2'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_previous', to='dispatching.Event'),
        ),
    ]
