# Generated by Django 2.2.4 on 2021-02-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0004_auto_20210209_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_calls',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='date_calls',
        ),
        migrations.AddField(
            model_name='event',
            name='time_created_at',
            field=models.TimeField(blank=True, null=True, verbose_name='Время сообщения'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='time_created_at',
            field=models.TimeField(blank=True, null=True, verbose_name='Время сообщения'),
        ),
    ]
