# Generated by Django 2.2.4 on 2020-09-10 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0004_event_previous'),
        ('dispatching', '0004_auto_20200910_1510'),
    ]

    operations = [
    ]
