# Generated by Django 2.2.4 on 2020-09-29 12:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0004_auto_20200929_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_field', models.CharField(blank=True, max_length=100500, null=True, verbose_name='field_name')),
                ('changed_data', models.TextField()),
                ('chaged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_history', to='dispatching.Event')),
            ],
            options={
                'verbose_name': 'История событий',
                'verbose_name_plural': 'История событий',
            },
        ),
    ]
