# Generated by Django 2.2.4 on 2020-08-17 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_outfitworker'),
        ('dispatching', '0004_auto_20200817_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='point1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point1_event', to='objects.Point', verbose_name='Ип от'),
        ),
        migrations.AddField(
            model_name='event',
            name='point2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point2_event', to='objects.Point', verbose_name='Ип до'),
        ),
    ]
