# Generated by Django 2.2.4 on 2020-08-20 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0005_auto_20200817_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='comments',
        ),
        migrations.AddField(
            model_name='event',
            name='comments1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_comments1', to='dispatching.Comments', verbose_name='Примечание1'),
        ),
        migrations.AddField(
            model_name='event',
            name='comments2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_comments2', to='dispatching.Comments', verbose_name='Примечание2'),
        ),
    ]
