# Generated by Django 2.2.4 on 2021-03-31 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0005_auto_20210210_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='previous',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='previous',
        ),
    ]
