# Generated by Django 2.2.4 on 2020-09-29 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0005_eventhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='changed_field',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='changed_field',
        ),
        migrations.DeleteModel(
            name='EventHistory',
        ),
    ]
