# Generated by Django 2.2.4 on 2020-09-11 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0005_merge_20200910_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ips',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_ips', to='objects.Point', verbose_name='ИП'),
        ),
    ]
