# Generated by Django 2.2.4 on 2021-05-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0006_auto_20210331_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='arrival_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата приезда бригады'),
        ),
        migrations.AddField(
            model_name='event',
            name='downtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Длителность простоя'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='arrival_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата приезда бригады'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='downtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Длителность простоя'),
        ),
    ]
