# Generated by Django 2.2.4 on 2020-08-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0006_auto_20200820_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='comments1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Примечание1'),
        ),
        migrations.AlterField(
            model_name='event',
            name='comments2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Примечание2'),
        ),
    ]
