# Generated by Django 2.2.4 on 2021-05-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0007_auto_20210524_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='downtime',
            field=models.TimeField(blank=True, null=True, verbose_name='Длителность простоя'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='downtime',
            field=models.TimeField(blank=True, null=True, verbose_name='Длителность простоя'),
        ),
    ]
