# Generated by Django 2.2.4 on 2020-08-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название'),
        ),
    ]
