# Generated by Django 2.2.4 on 2021-05-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0008_auto_20210524_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='downtime',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Длителность простоя'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='downtime',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Длителность простоя'),
        ),
    ]
