# Generated by Django 2.2.4 on 2020-08-20 09:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0008_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type_journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatching.TypeOfJournal', verbose_name='Вид журнала'),
            preserve_default=False,
        ),
    ]
