# Generated by Django 2.2.4 on 2021-05-28 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_customer', '0006_auto_20210412_1237'),
        ('dispatching', '0009_auto_20210524_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='form_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_form_customer', to='form_customer.Form_Customer', verbose_name='События по арендаторам'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='form_customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='form_customer.Form_Customer', verbose_name='События по арендаторам'),
        ),
    ]
