# Generated by Django 2.2.4 on 2021-08-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0009_auto_20210524_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='calculate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='calculate',
            field=models.BooleanField(default=True),
        ),
    ]
