# Generated by Django 2.2.4 on 2021-08-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0010_auto_20210817_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='calculate',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='calculate',
        ),
        migrations.AddField(
            model_name='event',
            name='bypass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='bypass',
            field=models.BooleanField(default=False),
        ),
    ]
