# Generated by Django 2.2.4 on 2020-08-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0012_auto_20200824_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time_period',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Сумма часов, за которое устранили аварию'),
        ),
    ]
