# Generated by Django 2.2.4 on 2020-08-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0014_auto_20200827_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time_period',
        ),
        migrations.AddField(
            model_name='event',
            name='period_of_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Сумма часов, за которое устранили аварию'),
        ),
    ]
