from django.contrib import admin
from .models import *

admin.site.register(TraktOrLine)
admin.site.register(InOut)
admin.site.register(Measure)
admin.site.register(Speed)
admin.site.register(TPO)
admin.site.register(TypeOfTrakt)
admin.site.register(Type)
admin.site.register(TypeOfLocation)
admin.site.register(Customer)
admin.site.register(Phone)
admin.site.register(LineType)
admin.site.register(Mode)
admin.site.register(Category)
admin.site.register(System)
admin.site.register(Outfit)
admin.site.register(Point)
admin.site.register(Object)
admin.site.register(IP)
admin.site.register(TransitObject)
admin.site.register(SubsRoutes)
admin.site.register(Circuit)
admin.site.register(Circuit1)
admin.site.register(Bypass)
admin.site.register(AssignPart)
admin.site.register(Trasa)