# Generated by Django 2.2.4 on 2020-09-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('id',), 'verbose_name': 'Арендатор', 'verbose_name_plural': 'Арендаторы'},
        ),
    ]
