# Generated by Django 2.2.4 on 2020-06-15 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Сигнализация',
                'verbose_name_plural': 'Сигнализация',
            },
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='adding',
            new_name='contact_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='connection_points',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='our_services_to',
        ),
        migrations.AddField(
            model_name='customer',
            name='amount_flow',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Количество потоков'),
        ),
        migrations.AddField(
            model_name='customer',
            name='comments',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='customer',
            name='num_order',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер распоряжения'),
        ),
        migrations.AddField(
            model_name='customer',
            name='order',
            field=models.ImageField(blank=True, null=True, upload_to='object/order/', verbose_name='Распоряжение'),
        ),
        migrations.AddField(
            model_name='customer',
            name='type_of_using',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вид использования'),
        ),
        migrations.AddField(
            model_name='customer',
            name='signalization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cust_sign', to='customer.Signalization'),
        ),
    ]
