# Generated by Django 2.2.4 on 2020-06-15 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200615_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='amount_flow',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='num_order',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='order',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='signalization',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='type_of_using',
        ),
        migrations.DeleteModel(
            name='Signalization',
        ),
    ]
