# Generated by Django 2.2.4 on 2020-11-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_historicalcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='diapozon',
            field=models.CharField(blank=True, max_length=1250, null=True, verbose_name='Диапозон нумераций'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='diapozon',
            field=models.CharField(blank=True, max_length=1250, null=True, verbose_name='Диапозон нумераций'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=1250, null=True, verbose_name='Email и телефон'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='email',
            field=models.CharField(blank=True, max_length=1250, null=True, verbose_name='Email и телефон'),
        ),
    ]
