# Generated by Django 2.2.4 on 2020-06-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200615_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='adding',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Примечание'),
        ),
    ]
