# Generated by Django 2.2.4 on 2021-02-10 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20201120_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='reuisits',
        ),
        migrations.RemoveField(
            model_name='historicalcustomer',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='historicalcustomer',
            name='reuisits',
        ),
    ]
