# Generated by Django 2.2.4 on 2020-03-29 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
        ('form51', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form51',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.Object'),
        ),
        migrations.AddField(
            model_name='form51',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_form51', to='form51.Region'),
        ),
        migrations.AddField(
            model_name='form51',
            name='trassa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trassa_form51', to='objects.Trassa'),
        ),
    ]
