# Generated by Django 2.2.4 on 2020-04-14 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
        ('form51', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form51',
            name='point1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form51_point', to='objects.Point', verbose_name='ИП приема'),
        ),
        migrations.AddField(
            model_name='form51',
            name='point2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form51_point2', to='objects.Point', verbose_name='ИП пер'),
        ),
        migrations.AddField(
            model_name='form51',
            name='tpo1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form51_tpo', to='objects.TPO'),
        ),
        migrations.AddField(
            model_name='form51',
            name='tpo2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form51_tpo2', to='objects.TPO'),
        ),
        migrations.AddField(
            model_name='form51',
            name='type_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form51_type_line', to='objects.LineType'),
        ),
    ]
