# Generated by Django 2.2.4 on 2020-04-20 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form51', '0002_auto_20200414_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form51Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form51.Region')),
            ],
            options={
                'verbose_name': 'Категории Формы 5.1.',
                'verbose_name_plural': 'Категории Формы 5.1.',
            },
        ),
        migrations.AddField(
            model_name='form51',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_form51', to='form51.Form51Location'),
        ),
    ]
