# Generated by Django 2.2.4 on 2020-07-16 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('circuits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form53',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('circuit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='circuits.Circuit', verbose_name='Каналы')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
            options={
                'verbose_name': 'Форма 5.3',
                'verbose_name_plural': 'Форма 5.3.',
            },
        ),
        migrations.CreateModel(
            name='Schema53Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.ImageField(blank=True, null=True, upload_to='object/schema/', verbose_name='Схема')),
                ('form53', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schema53_photo', to='form53.Form53', verbose_name='Схема')),
            ],
        ),
        migrations.CreateModel(
            name='Order53Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ImageField(blank=True, null=True, upload_to='object/order/', verbose_name='Схема')),
                ('form53', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order53_photo', to='form53.Form53', verbose_name='Распоряжение')),
            ],
        ),
    ]
