# Generated by Django 2.2.4 on 2020-06-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form53', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form53',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
