# Generated by Django 2.2.4 on 2020-07-19 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form53', '0002_auto_20200717_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order53photo',
            name='form53',
        ),
        migrations.AddField(
            model_name='order53photo',
            name='form53',
            field=models.ManyToManyField(blank=True, null=True, related_name='order53_photo', to='form53.Form53', verbose_name='Распоряжение'),
        ),
        migrations.AlterField(
            model_name='order53photo',
            name='src',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='object/order/', verbose_name='Схема'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='schema53photo',
            name='form53',
        ),
        migrations.AddField(
            model_name='schema53photo',
            name='form53',
            field=models.ManyToManyField(blank=True, null=True, related_name='schema53_photo', to='form53.Form53', verbose_name='Схема'),
        ),
    ]
