# Generated by Django 2.2.4 on 2020-07-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form53', '0003_auto_20200719_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order53photo',
            name='form53',
            field=models.ManyToManyField(blank=True, related_name='order53_photo', to='form53.Form53', verbose_name='Распоряжение'),
        ),
        migrations.AlterField(
            model_name='schema53photo',
            name='form53',
            field=models.ManyToManyField(blank=True, related_name='schema53_photo', to='form53.Form53', verbose_name='Схема'),
        ),
    ]
