# Generated by Django 2.2.4 on 2020-11-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form53', '0003_auto_20201130_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order53photo',
            name='src',
            field=models.FileField(blank=True, upload_to='files/', verbose_name='Схема'),
        ),
        migrations.AlterField(
            model_name='schema53photo',
            name='src',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Схема'),
        ),
    ]
