# Generated by Django 2.2.4 on 2021-01-04 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form53', '0004_auto_20201130_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order53photo',
            name='form53',
        ),
        migrations.AddField(
            model_name='order53photo',
            name='form53',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order53_photo', to='form53.Form53', verbose_name='Распоряжение'),
        ),
        migrations.RemoveField(
            model_name='schema53photo',
            name='form53',
        ),
        migrations.AddField(
            model_name='schema53photo',
            name='form53',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schema53_photo', to='form53.Form53', verbose_name='Схема'),
        ),
    ]
