# Generated by Django 2.2.4 on 2020-10-19 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('accounts', '0001_initial'),
        ('circuits', '0001_initial'),
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_flow', models.CharField(blank=True, max_length=200, null=True, verbose_name='Количество потоков')),
                ('type_of_using', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вид использования')),
                ('num_order', models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер распоряжения')),
                ('comments', models.CharField(blank=True, max_length=250, null=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('circuit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='circuits.Circuit', verbose_name='Каналы')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('object', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.Object', verbose_name='КО')),
            ],
            options={
                'verbose_name': 'Форма для Арендаторов',
                'verbose_name_plural': 'Форма для Арендаторов',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Signalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Сигнализация',
                'verbose_name_plural': 'Сигнализация',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='OrderCusPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ImageField(blank=True, null=True, upload_to='object/order/', verbose_name='Схема')),
                ('form_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_cust_photo', to='form_customer.Form_Customer', verbose_name='Распоряжение')),
            ],
        ),
        migrations.AddField(
            model_name='form_customer',
            name='signalization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cust_sign', to='form_customer.Signalization'),
        ),
    ]
