# Generated by Django 2.2.4 on 2021-08-17 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circuits', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_flow', models.CharField(blank=True, max_length=200, null=True, verbose_name='Количество потоков')),
                ('type_of_using', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вид использования')),
                ('num_order', models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер распоряжения')),
                ('comments', models.CharField(blank=True, max_length=250, null=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('circuit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='circuits.Circuit', verbose_name='Каналы')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile')),
                ('object', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.Object', verbose_name='КО')),
                ('point1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_cust_point', to='objects.Point', verbose_name='ИП от')),
                ('point2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_cust_point2', to='objects.Point', verbose_name='ИП до')),
            ],
            options={
                'verbose_name': 'Форма для Арендаторов',
                'verbose_name_plural': 'Форма для Арендаторов',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Signalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Сигнализация',
                'verbose_name_plural': 'Сигнализация',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='OrderCusPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Схема')),
                ('form_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_cust_photo', to='form_customer.Form_Customer', verbose_name='Распоряжение')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalForm_Customer',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('amount_flow', models.CharField(blank=True, max_length=200, null=True, verbose_name='Количество потоков')),
                ('type_of_using', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вид использования')),
                ('num_order', models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер распоряжения')),
                ('comments', models.CharField(blank=True, max_length=250, null=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('circuit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='circuits.Circuit', verbose_name='Каналы')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.Profile')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history_form_customer_log', to='form_customer.Form_Customer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='objects.Object', verbose_name='КО')),
                ('point1', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='objects.Point', verbose_name='ИП от')),
                ('point2', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='objects.Point', verbose_name='ИП до')),
                ('signalization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='form_customer.Signalization')),
            ],
            options={
                'verbose_name': 'historical Форма для Арендаторов',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='form_customer',
            name='signalization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cust_sign', to='form_customer.Signalization'),
        ),
    ]
