# Generated by Django 2.2.4 on 2020-09-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form_customer',
            options={'ordering': ('id',), 'verbose_name': 'Форма для Арендаторов', 'verbose_name_plural': 'Форма для Арендаторов'},
        ),
        migrations.AlterModelOptions(
            name='signalization',
            options={'ordering': ('id',), 'verbose_name': 'Сигнализация', 'verbose_name_plural': 'Сигнализация'},
        ),
    ]
