# Generated by Django 2.2.4 on 2021-08-31 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_customer',
            name='object',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_customer', to='objects.Object', verbose_name='КО'),
        ),
    ]
