# Generated by Django 2.2.4 on 2020-08-21 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_customer', '0002_auto_20200820_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_customer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='form_customer',
            name='signalization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cust_sign', to='form_customer.Signalization'),
        ),
    ]
