# Generated by Django 2.2.4 on 2020-11-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_customer', '0002_historicalform_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercusphoto',
            name='order',
            field=models.ImageField(blank=True, null=True, upload_to='files/', verbose_name='Схема'),
        ),
    ]
