# Generated by Django 2.2.4 on 2020-11-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_customer', '0003_auto_20201130_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercusphoto',
            name='order',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Схема'),
        ),
    ]
