# Generated by Django 2.2.4 on 2020-12-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_customer', '0004_auto_20201130_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordercusphoto',
            old_name='order',
            new_name='src',
        ),
    ]
