# Generated by Django 2.2.4 on 2021-04-12 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0028_auto_20210405_1515'),
        ('form_customer', '0005_auto_20201224_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_customer',
            name='point1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_cust_point', to='objects.Point', verbose_name='ИП от'),
        ),
        migrations.AddField(
            model_name='form_customer',
            name='point2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_cust_point2', to='objects.Point', verbose_name='ИП до'),
        ),
        migrations.AddField(
            model_name='historicalform_customer',
            name='point1',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='objects.Point', verbose_name='ИП от'),
        ),
        migrations.AddField(
            model_name='historicalform_customer',
            name='point2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='objects.Point', verbose_name='ИП до'),
        ),
    ]
