# Generated by Django 2.2.4 on 2021-06-02 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_customer', '0006_auto_20210412_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_customer',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='historicalform_customer',
            name='customer',
        ),
    ]
