# Generated by Django 2.2.4 on 2021-06-01 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210210_1441'),
        ('form_customer', '0007_auto_20210601_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_customer',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='historicalform_customer',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer.Customer'),
        ),
    ]
