# Generated by Django 2.2.4 on 2020-03-31 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='maker_trassa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maker', to='accounts.Profile'),
        ),
    ]
