# Generated by Django 2.2.4 on 2020-04-19 07:30

from django.db import migrations
import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField

class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        AlterSortedManyToManyField(
            model_name='object',
            name='transit',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='transit_obj1', to='objects.Object'),
        ),
        AlterSortedManyToManyField(
            model_name='object',
            name='transit2',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='transit_obj2', to='objects.Object'),
        ),
    ]
