# Generated by Django 2.2.4 on 2020-03-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trassa',
            unique_together=set(),
        ),
    ]
