# Generated by Django 2.2.4 on 2020-04-19 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_auto_20200419_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='add_time',
        ),
    ]
