# Generated by Django 2.2.4 on 2020-03-02 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_auto_20200302_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='tpo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_tpo', to='objects.TPO'),
        ),
        migrations.AlterField(
            model_name='tpo',
            name='tpo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Индекс'),
        ),
    ]
