# Generated by Django 2.2.4 on 2020-03-31 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_object_maker_trassa'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='object',
            order_with_respect_to='transit2',
        ),
    ]
