# Generated by Django 2.2.4 on 2020-03-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_auto_20200327_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trassa',
            name='name',
            field=models.CharField(blank=True, max_length=1000000, null=True, verbose_name='Трасса'),
        ),
    ]
