# Generated by Django 2.2.4 on 2020-03-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_auto_20200311_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='trakt_line',
        ),
        migrations.AddField(
            model_name='object',
            name='add_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='trakt',
            field=models.BooleanField(blank=True, null=True, verbose_name='Тракт/Линия'),
        ),
        migrations.DeleteModel(
            name='TraktOrLine',
        ),
    ]
