# Generated by Django 2.2.4 on 2020-03-02 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_auto_20200302_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='tpo',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='objects.TPO'),
        ),
    ]
