# Generated by Django 2.2.4 on 2020-03-31 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_auto_20200331_1516'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='object',
            order_with_respect_to=None,
        ),
    ]
