# Generated by Django 2.2.4 on 2020-03-02 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_auto_20200302_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='type_outfit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='out_tpo', to='objects.TypeOfLocation'),
        ),
    ]
