# Generated by Django 2.2.4 on 2020-03-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_auto_20200323_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='id_transit1',
        ),
        migrations.RemoveField(
            model_name='object',
            name='id_transit2',
        ),
        migrations.AddField(
            model_name='object',
            name='transit',
            field=models.ManyToManyField(blank=True, related_name='transit_obj1', to='objects.Object'),
        ),
        migrations.AddField(
            model_name='object',
            name='transit2',
            field=models.ManyToManyField(blank=True, related_name='transit_obj2', to='objects.Object'),
        ),
    ]
