# Generated by Django 2.2.4 on 2020-03-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_form51_region'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form51',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
