# Generated by Django 2.2.4 on 2020-03-02 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_auto_20200302_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='id_outfit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_out', to='objects.Outfit'),
        ),
        migrations.AlterField(
            model_name='point',
            name='tpo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_tpo', to='objects.TPO'),
        ),
    ]
